### ISSUE TITLE
Does this only allow running Firefox?

### ISSUE THREAD

**Issue by julkhami** [jlesage/docker-firefox#104]
I’m new to Docker. Is it possible to have a Docker file which is just like an operating system in that it contains all the software dependencies you need - applications like Firefox, command line tools like apt, etc - or do you have one Docker container for one application? I.e. it seems here like this Docker container is only for running Firefox. But if I have a pre-existing Docker container, can I just add in Firefox functionality there?

**Comment by jlesage** [comment]
Yes, this container il only for Firefox.  Most of the time, containers are implementing a single application.

For what you are looking for, why are you not using a virtual machine instead ?
