### ISSUE TITLE
Possibility to set HTTP[s] proxy by env variable

### ISSUE THREAD

**Issue by limosek** [jlesage/docker-firefox#11]
It would help a lot if there is env variable for docker to set http[s] proxy settings.
HTTP_PROXY=http://proxy:port HTTPS_PROXY=http://proxy:port docker run ...

Should be easy script which will update prefs.js like https://stackoverflow.com/questions/843340/firefox-proxy-settings-via-command-line

Thank you!

**Comment by jlesage** [comment]
Hi,

So what would be the benefit vs configuring the proxy in Firefox directly?

**Comment by limosek** [comment]
We are working on Lethean VPN docker image. It uses either proxied or routed mode for VPN. We like idea to have clean box with firefox for users. But we need to orchestrate it somehow so if we run both docker images, it will be preconfigured so lethean-vpn client will use firefox container which will point to lethean-vpn as proxy.

Best approach here would be to set generic algorithm how to map env variables to pref vaules. I can help with scripting if you wish.

lethean-vpn feature: https://github.com/LetheanMovement/lethean-vpn/issues/50

**Comment by jlesage** [comment]
That make sense.
I'm currently working on an update to the container.  I should be able to include this feature request as well.

**Comment by jlesage** [comment]
With the latest version, it is possible to set preferences via environment variables!
