### ISSUE TITLE
Session duplicating.

### ISSUE THREAD

**Issue by Kesavangk93** [jlesage/docker-firefox#111]
After make the docker up and run when i tried to launch the same in my browser. Firefox instance is running properly. Say an example: i am using chrome and opened few tab after launching the app(localhost:5800).

issue 1: When i reload or close and reopen the same link all previous tabs are present it is not closing the opens tabs.
issue 2: When i try to load the same link in 2 browsers (chrome and firefox) sessions are duplicating.

Need helping hands to resolve the issue?

**Comment by jlesage** [comment]
The container itself always run, even if you don't access it via http://localhost:5800.  All accesses to localhost:5800 connect to the same container instance.

So if you use Chrome to access the container and open 2 tabs to http://localhost:5800, both tabs will show the same thing.
Closing these Chrome tabs won't affect the container.  Thus, tabs opened in Firefox (in container) won't be affected.

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
