### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by hgpuke** [jlesage/docker-firefox#114]
Hi!
I am running your container on a Linux server at home.
My purpose of using it is to be able to manage the server and other resources in my home network, while I am not at home.
I have set up a subdomain for the Firefox web-page so that I can access it from anywhere (via a reverse proxy).
I have noticed that when accessing Firefox from work, and displaying the Cockpit management interface for my server, if a collegue of mine also goes to the firefox page, he is also automatically logged in to the Cockpit management interface. Basically any page that Firefox is displaying for me can also be seen by my collegue. This is a high security risk for me. Is there any way to prevent this?

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
