### ISSUE TITLE
build error: curl: (6) Could not resolve host: codeload.github.com

### ISSUE THREAD

**Issue by nicootje55** [jlesage/docker-firefox#115]
Hello,

I want to make small changes to your image by making some changes to your Dockerfile.
 
I started with your full code without changes to look or it would work.

command: 
docker build .

Log with error:
#7 18.62 Executing ca-certificates-20211220-r0.trigger
#7 18.78 OK: 261 MiB in 131 packages
curl: (6) Could not resolve host: codeload.github.com                      ## %-=O=-                         #     #     #     #
#7 28.38
#7 28.38 tar: invalid magic
#7 28.38 tar: short read
------
executor failed running [/bin/sh -c add-pkg --virtual build-dependencies         curl         build-base         &&     mkdir jsonlz4 &&     mkdir lz4 &&     curl -# -L {$JSONLZ4_URL} | tar xz --strip 1 -C jsonlz4 &&     curl -# -L {$LZ4_URL} | tar xz --strip 1 -C lz4 &&     mv jsonlz4/src/ref_compress/*.c jsonlz4/src/ &&     cp lz4/lib/lz4.* jsonlz4/src/ &&     cd jsonlz4 &&     gcc -static -Wall -o dejsonlz4 src/dejsonlz4.c src/lz4.c &&     gcc -static -Wall -o jsonlz4 src/jsonlz4.c src/lz4.c &&     strip dejsonlz4 jsonlz4 &&     cp -v dejsonlz4 /usr/bin/ &&     cp -v jsonlz4 /usr/bin/ &&     cd .. &&     del-pkg build-dependencies &&     rm -rf /tmp/* /tmp/.[!.]*]: exit code: 1

Can someone please give me a hint what i am doing wrong?

Thanks in advance,

Nico

**Comment by jlesage** [comment]
You have the same problem every time you try to build ?

The error indicate that `codeload.github.com` cannot be resolved.  Can the name be resolved if you run `nslookup codeload.github.com` ?

**Comment by nicootje55** [comment]
Thanks for your quick reply.

You pointed me to the right direction.

nslookup codeload.github.com gave Server: Unknown. 
In fact it gave this error for every server.
I tried it for 3 days without suc6.
But just now it worked like a charme.
 
I will invistigate why this happened.

But this issue can be closed.

**Comment by nicootje55** [comment]
Today i got the same problem wit nslookup. Server unknown.

The solution that worked is to diable IP V6 on my network-adapter.

I do not like this solution but at the moment i do nothing with IP V6 so i can live with it.
