### ISSUE TITLE
Firefox docker has issues 

### ISSUE THREAD

**Issue by sojab0on** [jlesage/docker-firefox#116]
I installed the docker with the command in the guide but the logs in the container state the fowllowing 

      
04/03/2022 14:31:38      moved window is released in the new position.

04/03/2022 14:31:38   Also see the -help entry for tuning parameters.

04/03/2022 14:31:38   You can press 3 Alt_L's (Left "Alt" key) in a row to 

04/03/2022 14:31:38   repaint the screen, also see the -fixscreen option for

04/03/2022 14:31:38   periodic repaints.

04/03/2022 14:31:38 GrabServer control via XTEST.

04/03/2022 14:31:38 

04/03/2022 14:31:38 Scroll Detection: -scrollcopyrect mode is in effect to

04/03/2022 14:31:38   use RECORD extension to try to detect scrolling windows

04/03/2022 14:31:38   (induced by either user keystroke or mouse input).

04/03/2022 14:31:38   If this yields undesired behavior (poor response, painting

04/03/2022 14:31:38   errors, etc) it may be disabled via: '-noscr'

04/03/2022 14:31:38   Also see the -help entry for tuning parameters.

04/03/2022 14:31:38   You can press 3 Alt_L's (Left "Alt" key) in a row to 

04/03/2022 14:31:38   repaint the screen, also see the -fixscreen option for

04/03/2022 14:31:38   periodic repaints.

04/03/2022 14:31:38 

04/03/2022 14:31:38 XKEYBOARD: number of keysyms per keycode 7 is greater

04/03/2022 14:31:38   than 4 and 51 keysyms are mapped above 4.

04/03/2022 14:31:38   Automatically switching to -xkb mode.

04/03/2022 14:31:38   If this makes the key mapping worse you can

04/03/2022 14:31:38   disable it with the "-noxkb" option.

04/03/2022 14:31:38   Also, remember "-remap DEAD" for accenting characters.

04/03/2022 14:31:38 

04/03/2022 14:31:38 X FBPM extension not supported.

Xlib:  extension "DPMS" missing on display ":0".

04/03/2022 14:31:38 X display is not capable of DPMS.

04/03/2022 14:31:38 --------------------------------------------------------

04/03/2022 14:31:38 

04/03/2022 14:31:38 Default visual ID: 0x21

04/03/2022 14:31:38 Read initial data from X display into framebuffer.

04/03/2022 14:31:38 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120

04/03/2022 14:31:38 

04/03/2022 14:31:38 X display :0 is 32bpp depth=24 true color

04/03/2022 14:31:38 

04/03/2022 14:31:38 Listening for VNC connections on TCP port 5900

04/03/2022 14:31:38 

04/03/2022 14:31:38 Xinerama is present and active (e.g. multi-head).

04/03/2022 14:31:38 Xinerama: number of sub-screens: 1

04/03/2022 14:31:38 Xinerama: no blackouts needed (only one sub-screen)

04/03/2022 14:31:38 

04/03/2022 14:31:38 fb read rate: 1213 MB/sec

04/03/2022 14:31:38 fast read: reset -wait  ms to: 10

04/03/2022 14:31:38 fast read: reset -defer ms to: 10

04/03/2022 14:31:38 The X server says there are 10 mouse buttons.

04/03/2022 14:31:38 screen setup finished.

04/03/2022 14:31:38 

The VNC desktop is:      72da906e3f1b:0



0

******************************************************************************

Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster

retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.

More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

Mozilla Firefox 94.0

04/03/2022 14:34:31 Got connection from client 127.0.0.1

04/03/2022 14:34:31   other clients:

04/03/2022 14:34:31 Got 'ws' WebSockets handshake

04/03/2022 14:34:31 Got protocol: binary

04/03/2022 14:34:31   - webSocketsHandshake: using binary/raw encoding

04/03/2022 14:34:31   - WebSockets client version hybi-13

04/03/2022 14:34:31 Disabled X server key autorepeat.

04/03/2022 14:34:31   to force back on run: 'xset r on' (3 times)

04/03/2022 14:34:31 incr accepted_client=1 for 127.0.0.1:45976  sock=10

04/03/2022 14:34:32 created   xdamage object: 0x40002c

04/03/2022 14:34:40 created selwin: 0x40002d

04/03/2022 14:34:40 called initialize_xfixes()

04/03/2022 14:34:49 cutbuffer_send: no send: uninitialized clients

04/03/2022 14:36:01 Got connection from client 127.0.0.1

04/03/2022 14:36:01   other clients:

04/03/2022 14:36:01      127.0.0.1

04/03/2022 14:36:01 Got 'ws' WebSockets handshake

04/03/2022 14:36:01 Got protocol: binary

04/03/2022 14:36:01   - webSocketsHandshake: using binary/raw encoding

04/03/2022 14:36:01   - WebSockets client version hybi-13

04/03/2022 14:36:01 incr accepted_client=2 for 127.0.0.1:46168  sock=11

04/03/2022 14:36:02 rfbProcessClientProtocolVersion: client gone

04/03/2022 14:36:02 client_count: 1

04/03/2022 14:36:02 Client 127.0.0.1 gone

04/03/2022 14:36:02 Statistics             events    Transmit/ RawEquiv ( saved)

04/03/2022 14:36:02  TOTALS              :      0 |         0/        0 (  0.0%)

04/03/2022 14:36:02 Statistics             events    Received/ RawEquiv ( saved)

04/03/2022 14:36:02  TOTALS              :      0 |         0/        0 (  0.0%)

04/03/2022 14:37:31 rfbProcessClientProtocolVersion: client gone

04/03/2022 14:37:31 client_count: 0

04/03/2022 14:37:31 Restored X server key autorepeat to: 1

04/03/2022 14:37:31 Client 127.0.0.1 gone

04/03/2022 14:37:31 Statistics             events    Transmit/ RawEquiv ( saved)

04/03/2022 14:37:31  TOTALS              :      0 |         0/        0 (  0.0%)

04/03/2022 14:37:31 Statistics             events    Received/ RawEquiv ( saved)

04/03/2022 14:37:31  TOTALS              :      0 |         0/        0 (  0.0%)

04/03/2022 14:37:32 destroyed xdamage object: 0x40002c

also when is go to de ip:5800 it loads for some time and them states server discnected 

the docker instance it runs on is a Ubuntu 20.04.3 LTS with desktop 

its running on the latstest docker and docker compose with portainer as management interface on top

**Comment by jlesage** [comment]
I see nothing wrong with the log.

I assume the "server disconnected" message is shown by the web interface ?  Do you have the same problem when accessing in a private/incognito window ?  If not, try to clear your browser's cache.

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
