### ISSUE TITLE
Passing an URL

### ISSUE THREAD

**Issue by rponline345** [jlesage/docker-firefox#119]
Hello,

is possible to pass an start URL, which will be loaded in the container on startup ?

Regards,
Robert

**Comment by JamesYuan** [comment]
-e FF_HOME_PAGE=https://google.com

**Comment by MysticNynja** [comment]
This is not working for me at all.  I pass in the -e and nothing happens.

Here is my cmd

docker run -d --name=firefox -p 5800:5800 -v /docker/appdata/firefox:/config:rw --shm-size 2g -e FF_HOME_PAGE=https://www.google.com jlesage/firefox

**Comment by enk21** [comment]
-e "FF_PREF_WELCOME_URL=startup.homepage_welcome_url=\"https://google.com\""

**Comment by jlesage** [comment]
Implemented in latest image.
