### ISSUE TITLE
Predefined Search term

### ISSUE THREAD

**Issue by joyskmathew** [jlesage/docker-firefox#122]
Is there any way we can automatically open a particular search term in the firefox docker

can anyone provide me with some help?

Each and every time whenever I run the docker image, I should be able to send a search term to search in the docker browser automatically when the browser opens

**Comment by jlesage** [comment]
Do you know how this is done with a "normal" (non-docker) Firefox ?

**Comment by jlesage** [comment]
Are you talking about the `--search <term>` parameter ?

**Comment by jlesage** [comment]
Ok, thanks for the update.
