### ISSUE TITLE
Some characters is not printing

### ISSUE THREAD

**Issue by Pin80** [jlesage/docker-firefox#123]
It's not issue of this project, but a problem was inherited by them. It's problem of vncserver (x11vnc), but author didn't answer.
x11vnx works fine on english layout, but if me need to type cyrillic characters than some characters is not printing.
https://github.com/LibVNC/x11vnc/issues/23
I found out how to solve a problem: 
apk add setxkbmap
setxkbmap ru
but it's  annoying.

Another aouthor found out earlier, that problem in keyboard.c file
Problem was solved by increasing size of array.
Could you make jlesage firefox with custom x11vnc ?

**Comment by jlesage** [comment]
Latest image no longer use x11vnc.  Can you check if this is still an issue ?
