### ISSUE TITLE
hardware acceleration not working

### ISSUE THREAD

**Issue by joraCardan5** [jlesage/docker-firefox#124]
Hi!

Great container. but I've noticed hwa is not working so neither dependent features like WebGL. 

On linux host with intel integrated graphics I've shared /dev/dri as suggested on some forums, but that didn't work, I think something else is missing - in about:support it still shows WebRender (software)

Any suggestions on this?

Thanks,
Daniel

**Comment by mrtnd** [comment]
Hi great container!! Use it on daily basis.

I have also tried to enable HWA by exposing /dev/dri to the container but that did not do the trick as mentioned by @joraCardan5

**Comment by mrtnd** [comment]
just checked if the mesa driver is installed. It wasn't.  From inside the container run `apk update && apk add mesa-dri-gallium`. with the driver installed, WebGL Driver is recognized in about:support.  @jlesage can you add it with the next release?

**Comment by jlesage** [comment]
@mrtnd, do you still get software rendering with the driver installed ?

**Comment by joraCardan5** [comment]
> > @mrtnd, do you still get software rendering with the driver installed ?
> 
> Hi, yes just installing the driver wont enable HW acceleration. ...

Thank you very much, it works, and now I finally have hwa and web gl working. 
Case solved, thanks
