### ISSUE TITLE
Open Range Port

### ISSUE THREAD

**Issue by jamuanfc** [jlesage/docker-firefox#126]
Hi, 

Lets say I have 100 users, is it possible to open range port 5800 to 5899 for docker firefox?

So user1 gets 5800, user2 gets 5801, user3 gets 5802 and so on.

Thanks..

**Comment by jlesage** [comment]
I guess that you want each user to have their own Firefox instance.  In this case, you need to create a container for each user and map port 5800 to a different port on the host.

**Comment by jamuanfc** [comment]
thanks
