### ISSUE TITLE
compil RPI

### ISSUE THREAD

**Issue by alexblav81** [jlesage/docker-firefox#13]
Hello, 

thanks for your job

I don't speak english sorry,
I would like compile your project to RPI and I have issues in more fonction:
````
xevents.c: In function 'check_autorepeat':
xevents.c:1138:7: warning: 'XKeycodeToKeysym' is deprecated [-Wdeprecated-declarations]
       str = XKeysymToString(XKeycodeToKeysym(dpy, i, 0));
       ^~~
In file included from x11vnc.h:77:0,
                 from xevents.c:35:
/usr/include/X11/Xlib.h:1687:15: note: declared here
 extern KeySym XKeycodeToKeysym(
               ^~~~~~~~~~~~~~~~
`````
have you solution?
I have search and  find this 
````
https://stackoverflow.com/questions/9838385/replace-of-xkeycodetokeysym
````
Can you help-me for debbug please

**Comment by jlesage** [comment]
What do you try to compile exactly?  This repo is for Firefox, but you seem to build the baseimage?

**Comment by alexblav81** [comment]
Yes sorry, I'm build baseimage exactly. Would you like i publish in other project?

**Comment by jlesage** [comment]
Yes I think it would be better.
