### ISSUE TITLE
KIOSK mode? 

### ISSUE THREAD

**Issue by chops888** [jlesage/docker-firefox#134]
Is there any way to pass standard FF command line params on launch? doesn't seem to be that I can find. --kiosk, specifically.

**Comment by jlesage** [comment]
Correct, there is currently no way to configure custom params.

Maybe we could add an environment variable to enable kiosk mode.  I guess you just need the `--kiosk` option with an URL ?

**Comment by chops888** [comment]
That would solve our particular issue, please and thanks!

Cheers



Chris Van Sickle
Resolve IT Consulting
***@***.***
250.882.0593
www.resolveITconsulting.ca



-------- Original message --------
From: Jocelyn Le Sage ***@***.***>
Date: 10/7/22 8:43 AM (GMT-08:00)
To: jlesage/docker-firefox ***@***.***>
Cc: Chris Van Sickle ***@***.***>, Author ***@***.***>
Subject: Re: [jlesage/docker-firefox] KIOSK mode? (Issue #134)


Correct, there is currently no way to configure custom params.

Maybe we could add an environment variable to enable kiosk mode. I guess you just need the --kiosk option with an URL ?

**Comment by jlesage** [comment]
Implemented in latest image.
