### ISSUE TITLE
Possible issue in ownership script

### ISSUE THREAD

**Issue by Chocolate-Banana** [jlesage/docker-firefox#135]
Hi

Since the update overnight, my firefox app had stopped working. 

It looks like it's this script running causing the issue:
![image](https://user-images.githubusercontent.com/43570997/194810737-d4ae10c0-82f1-4f74-92e8-f71186c351fc.png)

This keeps erroring: 
![image](https://user-images.githubusercontent.com/43570997/194810756-c4ebd087-f289-4a10-9e78-1ebd1e56e676.png)

Believe it might be down to something in the script. The files it was trying to change already were set to GUID of 1000. 

Firefox was working fine yesterday with same config. 
![image](https://user-images.githubusercontent.com/43570997/194811108-0a3df09f-4c17-41a6-af34-963501df99fc.png)

Taking the volume out fixes it. I will say though it is a great update so far with the scaling. Keep it up! :)

Cheers
Chris

**Comment by jlesage** [comment]
Thanks foe reporting.  What kind of folder is TrueNAS-Downloads?  Is it an SMB share?

**Comment by Chocolate-Banana** [comment]
It's an NFS share, it was working fine pre-update.

**Comment by jlesage** [comment]
Fixed in latest image.
