### ISSUE TITLE
Problem with Routing Based on URL Path

### ISSUE THREAD

**Issue by ctonton** [jlesage/docker-firefox#138]
I have followed the instructions in the README to set up a reverse proxy with Routing Based on URL Path in nginx, but no matter what I try, I am getting the same result. A red bar that says "X Failed to connect".  The container works fine alone and a reverse proxy with Routing Based on Hostname also works, but I need to be able to call multiple apps by URL path.

**Comment by jlesage** [comment]
Looks like the WebSocket connection fails.

Did you check the logs of your reverse proxy to see if there is any clue ?

**Comment by ctonton** [comment]
I started fresh in a virtual machine and have the same result. I can not tell what is happening. It looks like noVNC can not connect to the vncserver when using this type of reverse proxy. I have attached a copy of the log from nginx and a copy of my default site.
[access.txt](https://github.com/jlesage/docker-firefox/files/9771155/access.txt)
[default.txt](https://github.com/jlesage/docker-firefox/files/9771156/default.txt)

**Comment by ctonton** [comment]
And here is a copy of the nginx log from the container itself. I don't recognize the server ip address in this log
[access.txt](https://github.com/jlesage/docker-firefox/files/9771238/access.txt)

**Comment by jlesage** [comment]
Could you try with version 1.18.0 of the image to see if you have the same issue ?  This can be done by using the Docker image tag `v1.18.0`.

**Comment by ctonton** [comment]
I tested it and image v1.18.0 works fine. There must be something happening in the new version.

**Comment by jlesage** [comment]
Thanks of confirming.  I found the issue and will provide a fix.

**Comment by ctonton** [comment]
The newest version is now working.
