### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by ansorre** [jlesage/docker-firefox#14]
Hi, I'm trying to build this docker so far without any modification. Later I would like to make some modifications, but for now I get a problem and the build fails.
These are the errors I get:

Executing fontconfig-2.13.1-r0.trigger
Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found
Error relocating /lib/libuuid.so.1: getrandom: symbol not found
ERROR: fontconfig-2.13.1-r0.trigger: script exited with error 127
Executing gtk-update-icon-cache-2.24.32-r1.trigger
Error relocating /lib/libmount.so.1: getrandom: symbol not found
Error relocating /lib/libblkid.so.1: getrandom: symbol not found
Error relocating /lib/libuuid.so.1: getrandom: symbol not found
ERROR: gtk-update-icon-cache-2.24.32-r1.trigger: script exited with error 127
Executing mkfontscale-1.1.3-r0.trigger
Executing mkfontdir-1.0.7-r1.trigger
2 errors; 356 MiB in 161 packages
The command '/bin/sh -c add-pkg         desktop-file-utils         adwaita-icon-theme         ttf-dejavu         ffmpeg-libs         xdotool' returned a non-zero code: 2

I've tryed to search with google and to have a look at the Dockerfile, sorry, I'm also new to Docker. I really can't understand what's the problem. Error 127 is usually returned by the shell when a command is not found or is not executable, but that's all know.
Thanks anyway for this fantastic Docker.

**Comment by jlesage** [comment]
The problem is that the Firefox package in the Alpine edge repository is no longer compatible with stable Alpine versions.
I'm currently working on re-building Firefox against Alpine 3.8.  Once done, we will be able to re-build the Docker image successfully.

**Comment by Ansorre** [comment]
Thank you for your quick and kind reply jlesage.
