### ISSUE TITLE
json.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by dsrtusr88** [jlesage/docker-firefox#143]
![image](https://user-images.githubusercontent.com/33256205/197743692-04e45d04-8fb3-4af5-b612-9d1605cd36be.png)

Error box that persists and can't be cleared.  Comes with every clean set up.

**Comment by jlesage** [comment]
Could you provide the output of:
`docker exec <container name> cat /tmp/.web_data.json`

**Comment by dsrtusr88** [comment]
{
    "applicationName": "Firefox",
    "applicationVersion": "101.0.1-r0",
    "dockerImageVersion": "22.10.4",
    "darkMode": false
}

**Comment by jlesage** [comment]
Also, can you try to run:

`docker run --rm -p 5801:5800 jlesage/firefox`

Then access the container over port 5801 and verify if you get the problem.
Ctrl+c will terminate the above command.

**Comment by jlesage** [comment]
Btw, which browser are you using to access the container ?  Did you try another one?

**Comment by jlesage** [comment]
What version of Firefox and for which OS ?
Do you have the same issue when using a private window ?

**Comment by rjgould** [comment]
> What version of Firefox and for which OS ? Do you have the same issue when using a private window ?

Firefox is Version 107.0.1 (64-bit) on Windows 11.  It does it on both regular and private windows.  Doesn't happen in Edge.

The HTML for the message displayed appears to be: `
        <div>
            <div>Unexpected error encountered:</div>
            <br>
            <div id="noVNC_fallback_errormsg"><div class="noVNC_message">JSON.parse: unexpected character at line 1 column 1 of the JSON data</div></div>
        </div>
    `

Feels like Firefox is just displaying something it should not as everything else works.

**Comment by jlesage** [comment]
What is the version of the image you are currently using ?  You can see the image version from `docker logs <container name>`.

**Comment by jlesage** [comment]
(or by opening the left menu in the UI)

**Comment by rjgould** [comment]
> (or by opening the left menu in the UI)

Czkawka v5.0.2
Docker Image v22.12.1

**Comment by jlesage** [comment]
Do you have any plugin running that might interfere with the page ?
Do you still have the issue with the latest version ? If yes, could you open the developper tools in Firefox and report the errors under the Console tab ?

**Comment by dsrtusr88** [comment]
it was a plug-in, disabled it for that instance page and good to go!

**Comment by jlesage** [comment]
Thanks for the update ! Do you mind sharing the plugin that caused the issue ?
