### ISSUE TITLE
Running multiple instances on same host with different ports?

### ISSUE THREAD

**Issue by benjamin604** [jlesage/docker-firefox#147]
Hello, not really an issue, but more of a question.  I've got a single instance running on 5800, but would like to run another 3-5 instances from the same VM host. I tried just iterating all the ports, but while the docker starts, it doesn't work.

if I curl http://host-ip:5801, I get "Empty reply from server"

Anyone running multiple instances that could point me in the right direction?

Thanks,
Ben

**Comment by jlesage** [comment]
How did you created your containers ?  To have multiple instances, you should map port 5800 to a different port with the `-p` argument of the `docker run` command.

For example, the first instance could use `-p 5801:5800`, the second `-p 5802:5800`, etc.

**Comment by benjamin604** [comment]
Ah, I was running the following:

`sudo docker run -d  --name=firefox5800  -p 5800:5800  -v /docker/appdata/firefox5800:/config:rw  --shm-size 2g  jlesage/firefox`
`sudo docker run -d  --name=firefox5801  -p 5801:5801  -v /docker/appdata/firefox5801:/config:rw  --shm-size 2g  jlesage/firefox`
`sudo docker run -d  --name=firefox5801  -p 5802:5802  -v /docker/appdata/firefox5802:/config:rw  --shm-size 2g  jlesage/firefox`

I'll try your suggestion now, thank you!

**Comment by benjamin604** [comment]
your suggestion worked, thank you!

**Comment by jlesage** [comment]
You are welcome!
