### ISSUE TITLE
VNC_PASSWORD does not work for 2 and more instances

### ISSUE THREAD

**Issue by EvgeniyDoctor** [jlesage/docker-firefox#150]
I need to create multiple instances of firefox with VNC_PASSWORD but they do not work. If i run second firefox with VNC_PASSWORD, it tells me that firefox is already in use, and the first one show the password field again.
I don't know ahead of time how much instances i will need, so different config dirs is not an option.

To reproduce:
- create 2 containers with VNC_PASSWORD on different ports but with one config
- try to use it

Firefox v107.0.1-r1
Docker Image v22.12.2

**Comment by jlesage** [comment]
The `/config` folder is not meant to be shared across different container instances.

Is it mandatory that you map the `/config` folder ?

**Comment by EvgeniyDoctor** [comment]
I already solved this.
