### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by ezrix-jaafar** [jlesage/docker-firefox#155]
I'm greeting blank white screen when accessing my Firefox in browser

**Comment by jlesage** [comment]
Same as #152 ?  Does the UI show up after several minutes ?

**Comment by ezrix-jaafar** [comment]
Yeah same issue.. I see the clipboard panel but Firefox not loaded.

**Comment by jlesage** [comment]
This should now be fixed with the latest image.
