### ISSUE TITLE
cjk font is downloaded everytime when docker container restarts

### ISSUE THREAD

**Issue by tsurara-guobin** [jlesage/docker-firefox#157]
Every time my docker container restarts, 10-cjk-font.sh downloads cjk font. It takes a long time such that I have to wait for a long time to use service.
I found that the script "10-cjk-font.sh" check if font directory exists. However, it seems that the name of font directory installed does not match. My route is '/usr/share/fonts/wqy-zenhei' other than the route in script.

**Comment by jlesage** [comment]
Thanks for reporting.  I will fix this issue.

**Comment by jlesage** [comment]
This should be fixed with the latest image.
