### ISSUE TITLE
Synology and --shm-size ?

### ISSUE THREAD

**Issue by IceKaching** [jlesage/docker-firefox#16]
With Docker on Synology, what is the method to set the --shm-size?

**Comment by IceKaching** [comment]
Have launched it for now from shell with the following, but would be nice to have a method that doesn't require going down to that level.

docker run -d \
    --name=firefox2 \
    -e DISPLAY_WIDTH=1400 \
    -e DISPLAY_HEIGHT=900 \
    -p 5800:5800 \
    -p 5900:5900 \
    -v /volume2/docker/firefox:/config:rw \
    --shm-size 2g \
    jlesage/firefox:latest

**Comment by jlesage** [comment]
If the Synlogy UI doesn't have a way to manually configure custom parameters, then I guess the only choice you have is to start the container via the command line.

**Comment by IceKaching** [comment]
Customer parameters are okay on Synology, (e.g. DISPLAY_WIDTH, DISPLAY_HEIGHT, etc). However --shm-size is not a variable that it will accept since it only seems to be relevant with the run command (and that part you can't modify through the UI).

**Comment by jlesage** [comment]
Under the hood, Synology invoke the `docker run` command to create the container.

Settings like `DISPLAY_WIDTH` are in fact environment variables that are provided to the container and they are passed to the `docker run` command via `-e` arguments.  Since `--shm-size` is not an environment variable, it must be configured, via the UI, with another method.  But it seems that the Synology doesn't provide a such method...

**Comment by IceKaching** [comment]
Thank you. I think it's an enhancement that needs to be made on the Synology side.

Just as an FYI, it seems that you only need to do the `docker run` method one time - subsequent launches can be done from the Synology UI, and it keeps the shm size that was originally specified.

**Comment by DaVinci1987** [comment]
Are there any updates on how to Increasing Shared Memory Size in the Synology Docker app for Firefox?

**Comment by jlesage** [comment]
I don't know if it's now possible to set the parameter via the UI, but you can always set it by manually creating the container from the command line.

**Comment by C-Fu** [comment]
Suggestion: setting shm-size via environment would be preferable for synology-based devices. It's (relatively) easier/faster IMO to implement this vs waiting for syno to add this feature

**Comment by jlesage** [comment]
`--shm-size` is a Docker parameter that needs to passed when creating the container.  The container itself cannot control/change it (like the volumes).

**Comment by C-Fu** [comment]
I see. And I guess there's no way to set --shm-size 2G as the default then?

Oh well. Thanks anyway for the clarification!

**Comment by dabazti** [comment]
Hey there, had the same issue today and fixed it for me. After generation of the container via Synology UI you can change the shm size inside the hostconfig.json. Therefore:

1. SSH into your Synology
2. Stop docker service: `sudo synoservice --stop pkgctl-Docker`
3. Make yourself su (be really careful!): `sudo su`
4. Cd into your docker container, which should be located in /volume1/@docker/containers/CONTAINER ID
5. Open hostconfig.json: `vim hostconfig.json`
6. Change "ShmSize" to your preffered value, 1GB="ShmSize":1073741824
7. Save hostconfig.json
8. Exit su: `exit`
9. Start docker Service: `sudo synoservice --start pkgctl-Docker`

Hope that helps anyone in the future.

**Comment by tropisch** [comment]
> Hey there, had the same issue today and fixed it for me. After generation of the container via Synology UI you can change the shm size inside the hostconfig.json. Therefore:
> 
> 1. SSH into your Synology
> 2. Stop docker service: `sudo synoservice --stop pkgctl-Docker`
> 3. Make yourself su (be really careful!): `sudo su`
> 4. Cd into your docker container, which should be located in /volume1/@docker/containers/CONTAINER ID
> 5. Open hostconfig.json: `vim hostconfig.json`
> 6. Change "ShmSize" to your preffered value, 1GB="ShmSize":1073741824
> 7. Save hostconfig.json
> 8. Exit su: `exit`
> 9. Start docker Service: `sudo synoservice --start pkgctl-Docker`
> 
> Hope that helps anyone in the future.

Thanks man, that helped a alot!

**Comment by litio2001** [comment]
> 
> 
> Hey there, had the same issue today and fixed it for me. After generation of the container via Synology UI you can change the shm size inside the hostconfig.json. Therefore:
> 
>     1. SSH into your Synology
> 
>     2. Stop docker service: `sudo synoservice --stop pkgctl-Docker`
> 
>     3. Make yourself su (be really careful!): `sudo su`
> 
>     4. Cd into your docker container, which should be located in /volume1/@docker/containers/CONTAINER ID
> 
>     5. Open hostconfig.json: `vim hostconfig.json`
> 
>     6. Change "ShmSize" to your preffered value, 1GB="ShmSize":1073741824
> 
>     7. Save hostconfig.json
> 
>     8. Exit su: `exit`
> 
>     9. Start docker Service: `sudo synoservice --start pkgctl-Docker`
> 
> 
> Hope that helps anyone in the future.

thanks you so much!
