### ISSUE TITLE
Some unicode characters are not available

### ISSUE THREAD

**Issue by rydeordie99** [jlesage/docker-firefox#171]
When trying to access the webui of Transmission 4.0.2, some of the unicode characters are not working. Specifically the Black Up-Pointing Triangle (▲)

Is there a font pack I need to download or anything I can do on  my end to fix this?

**Comment by jlesage** [comment]
Thanks, this will be fixed in next version.

**Comment by jlesage** [comment]
Forgot to update this issue: this is fixed now.
