### ISSUE TITLE
.jsp webpage does not respond

### ISSUE THREAD

**Issue by joel72265** [jlesage/docker-firefox#178]
The .jsp page (https://businessonline.emiratesnbd.com) loads properly. After you enter data and click the 'Submit' button nothing happens. However, if you enter the same data on a Desktop Firefox bowser, on clicking Submit the page loads. (please send me an email joel72265@gmail.com if you need field data)

Docker Firefox 109.0.1

**Comment by jlesage** [comment]
If you open the developper tools, do you see any errors in the console ?

**Comment by jlesage** [comment]
Do you use the same Firefox version with the desktop browser ?

Looks like you are using 2 different Firefox versions that behave differently on errors caused by the website.

**Comment by joel72265** [comment]
yes, we were using a different Desktop browser. When we use a Desktop Firefox browser after we enter the details, we click the button and we can go to the next page. But in the docker Firefox, the button does not work/does not click

Docker Firefox 109.0.1
Desktop Firefox 112.0.1

**Comment by jlesage** [comment]
Did you try with Desktop Firefox 109.0.1 ?

**Comment by joel72265** [comment]
No, I did not. I tried with Desktop Firefox 112.0.1 which works. 
Today I tried with Desktop Firefox 109.0.1 which also works, if you need any additional details to test please share your email address so I can send you the credentials privately
