### ISSUE TITLE
docker pull on windows through firefox browser gcr.io image

### ISSUE THREAD

**Issue by trabuko** [jlesage/docker-firefox#180]
May I download this operation with this extension?. thanx. A  image about 14 GiB ?

**Comment by jlesage** [comment]
Sorry, I'm not sure I understand the question/problem...

**Comment by trabuko** [comment]
I:m trying to download gcr.io kaggle image and when execute *docker pull*
into Google console does not complete the task.

**Comment by trabuko** [comment]
An image perhaps better than muy poor explanation.

**Comment by jlesage** [comment]
Images are not seen via email.  You need to go through github.com to add it.

**Comment by trabuko** [comment]
as you can tell that I from github, I understand little
I hace uploaded to Drive and this ie a shortcut link:
https://drive.google.com/file/d/1XO1j4elnLrFiGoKL4a62cW0FHzSdtFy2/view?usp=drivesdk
In short:
https://n9.cl/x35mj
I Hope I've explained well enough. Thanx for your time a
And patience

**Comment by jlesage** [comment]
I would suggest that you check the available space on the device you try to install the Docker image.

But in any case, I don't see that your problem is related to this project...

**Comment by trabuko** [comment]
I didn't realize of no convenience. Sorry.
Beg your pardon, I've wasted your precious time.

**Comment by jlesage** [comment]
No problem!
