### ISSUE TITLE
Firefox version as environment variable

### ISSUE THREAD

**Issue by gadireis** [jlesage/docker-firefox#183]
### Idea

Is it possible to change the FIREFOX_VERSION argument to be an environment variable instead?
That way I could choose an older firefox version with the newer docker file?

**Comment by jlesage** [comment]
The Alpine repository doesn't allow to install/user older package versions.  Also, using a repository version that differs from the one used by the container is prone to errors and dependencies issues.

However, you can use an older docker image version that has the needed Firefox version.

**Comment by gadireis** [comment]
Right that works but i'd like to take advantage of the kiosk and open url variables that don't exist in older images

**Comment by jlesage** [comment]
You could edit `/startapp.sh` in the container and add `--kiosk` as a parameter of Firefox when starting it.  Same thing for the URL, where you can add it as the last argument of firefox.
