### ISSUE TITLE
Use latest version of firefox

### ISSUE THREAD

**Issue by olaxe** [jlesage/docker-firefox#19]
First, thanks for your docker Firefox, it rocks!
I tried to use the FIREFOX_VERSION=66.0.4-rc0 to have a most recent version of FF but without success. This package is in the repo [Alpine Testing](http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/) and you add it in the dockerfile:
```
RUN \
    add-pkg --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
            --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
            --upgrade firefox=${FIREFOX_VERSION}
```
I checked logs in the container and there is a lot of useful information but nothing on this part. It will great to have a log on the version of Firefox selected from the environment variable and the list of all FF versions available.

For me, to have the (al)most recent version of Firefox is really important as a lot of security fixes have been applied.

**Comment by jlesage** [comment]
Note that the Firefox version to use cannot be selected at runtime.  A new docker image is required when a new FF version is available.

I'm currently working to integrate the latest Firefox version.  A new image will be available soon.

**Comment by jlesage** [comment]
You should now be able to use the latest Firefox version with the updated docker image.

**Comment by olaxe** [comment]
thank you very much
