### ISSUE TITLE
[Feature request] Firefox ESR

### ISSUE THREAD

**Issue by IgitBuh** [jlesage/docker-firefox#194]
### Idea

Is there any chance you could provide Firefox ESR versions as well?

The reason for this request is that the normal Firefox version doesn't allow custom add-ons to be installed permanently. The debug option will remove the add-on on the next program start.

There is the option `xpinstall.signatures.required` in `about:config` that allows installing unsigned (custom/modified) add-ons permanently, but this setting is only used in the ESR, nightly and developer builds, but not in the normal release.

Sadly, there seems to be no docker hub project with either of those alternative versions.

Is there any chance you could add an ESR version branch to your project?

**Comment by jlesage** [comment]
Thanks for the suggestion.  Yes, I can provide the ESR version!

**Comment by jlesage** [comment]
Firefox ESR image is now available: https://hub.docker.com/r/jlesage/firefox-esr
