### ISSUE TITLE
[Feature request] I want more CJK font configuration

### ISSUE THREAD

**Issue by pdone** [jlesage/docker-firefox#197]
### Idea

I want to configure the CJK font download link, because it is slow to use the default download link in China.
In addition, can you add other fonts, such as Alibaba PuHuiTi.
-
我想要配置CJK字体下载链接，因为在中国使用默认的下载链接速度很慢。
另外，能否增加其他字体，比如阿里巴巴普惠体。

**Comment by jlesage** [comment]
> I want to configure the CJK font download link, because it is slow to use the default download link in China.

This is now possible via the `PACKAGES_MIRROR` environment variable.

> In addition, can you add other fonts, such as Alibaba PuHuiTi.

If the font is available in the Alpine Linux repository (https://pkgs.alpinelinux.org), you can install it via `INSTALL_PACKAGES` variable.  This would replace the `ENABLE_CJK_FONT` variable.

**Comment by pdone** [comment]
Thank you very much, I am already using this new feature.
