### ISSUE TITLE
[Feature request] Hope can use custom repo when install CJK

### ISSUE THREAD

**Issue by nibazshab** [jlesage/docker-firefox#199]
### Idea

In some countries, for some special reasons, cannot connect to `dl-cdn.alpinelinux.org`. So i hope can use custom repo

This is my idea:

Add a environment APKREPO, like `APKREPO=mirrors.aliyun.com`. And add a row like `if [ ! -z $APKREPO ]; then sed -i "s/dl-cdn.alpinelinux.org/$APKREPO/g" /etc/apk/repositories; fi` to _10-cjk-font.sh_

**Comment by nibazshab** [comment]
Maybe I can submit a pr, but I don't find 10-cjk-font.sh in this repo :

**Comment by jlesage** [comment]
This part is shared across multiple containers, both based on Alpine and Debian/Ubuntu.  So I will add a generic solution that works in all cases.

**Comment by jlesage** [comment]
`PACKAGES_MIRROR` environment variable can now be used for this purpose.
