### ISSUE TITLE
Pulseaudio (sound) in Firefox

### ISSUE THREAD

**Issue by ErgoProxy1337** [jlesage/docker-firefox#2]
Hey,
I am a real fan of your docker releases. U create exactly what I need :) but I am still not good enough to create my own stuf.

Do you think, it is possible to add sound in your Firefox too?
I found the following interesting links but its to hard for me to do it by myself.
[docker-pulseaudio-example](https://hub.docker.com/r/thebiggerguy/docker-pulseaudio-example/)
[tor-browser with uplseaudio](https://hub.docker.com/r/inglebard/tor-browser/)

that would be great

**Comment by jlesage** [comment]
Thanks for your suggestion!  I will look at it  to see what can be done.

**Comment by jlesage** [comment]
Fixed in version 1.3.0!
See https://github.com/jlesage/docker-firefox#sound-support
