### ISSUE TITLE
Unable to spawn /etc/logmonitor/notifications.d/shm_size/filter: Permission denied

### ISSUE THREAD

**Issue by Pubec** [jlesage/docker-firefox#20]
When I try to run docker-compose up, I get an error:  warning: unable to spawn /etc/logmonitor/notifications.d/shm_size/filter: Permission denied

My docker-compose.yml file:
version: '3'
services:  
    firefox1:  
      build:  
        context: .  
        args:  
          shm-size: 2g  
      ports:  
        - "5801:5800"  
      volumes:  
        - "/docker/appdata/firefox1:/config:rw"   
      deploy:  
        resources:  
          limits:  
            memory: 1G  
          reservations:  
            memory: 256M  
      environment:  
        KEEP_APP_RUNNING: 1

And by just running the docker run from README.md:
`docker run -d \
    --name=firefox \
    -p 5800:5800 \
    -v /docker/appdata/firefox:/config:rw \
    --shm-size 2g \
    jlesage/firefox`

everything work fine.

**Comment by jlesage** [comment]
Did you try a minimal compose file like this : https://github.com/jlesage/docker-firefox#docker-compose-file

**Comment by Pubec** [comment]
> 
> 
> Did you try a minimal compose file like this : https://github.com/jlesage/docker-firefox#docker-compose-file

Yes, I did. This is how my yml file looked like: 
```
version: '3'  
services:
  firefox1:
    build: .
    ports:
      - "5801:5800"
    volumes:
      - "/docker/appdata/firefox1:/config:rw"
```

After not passing the --shm-size 2g, I got an error: docker-firefox-master_firefox1_1 exited with code 126.

**Comment by Pubec** [comment]
Cloning fresh repo helped and started working. Thank you
