### ISSUE TITLE
Output of Console.log for developer

### ISSUE THREAD

**Issue by Okkbro501** [jlesage/docker-firefox#210]
### Idea

**Sir**,
Please add feature of extract output of every tab console.log in real timing

**Comment by jlesage** [comment]
Sorry can you provide more details ?  I'm not sure to understand what you are requesting.

**Comment by Okkbro501** [comment]
Thank you for your response.,,

Sir I want to say that,
I want to see output of console tab at terminal screen

**Comment by jlesage** [comment]
You mean that you want the content of console tab from Developer Tools to be also outputted in the container's log ?
I don't know if this is possible.  It would require Firefox to also output the console's content to its stdout, which I think is not possible today.

**Comment by Okkbro501** [comment]
Ok, thanks for the clarification.

**Comment by Okkbro501** [comment]
Very nice support team I ever seen
