### ISSUE TITLE
Open Links in Tabs instead of New Windows

### ISSUE THREAD

**Issue by angdigi** [jlesage/docker-firefox#23]
The setting "open links in tabs instead of new windows" doesn't always work. This wouldn't be an issue, but I'm not able to close the new window. Instead, I have to close all windows or reboot the container. If I leave the window open in the background, the container memory utilization will grow.

**Comment by jlesage** [comment]
Are the new windows opened automatically?  You could try to install the "Single Window" extension (https://add0n.com/single-window.html).

**Comment by angdigi** [comment]
They are not pop-ups if that's what you're asking. I'm referring to links that I click. I would expect the setting "open links in tabs instead of new windows" would prevent new windows. I tried the single-window add-on and that does not work either.

**Comment by jlesage** [comment]
So it's the website that instruct the browser to open the link in a new window?

**Comment by angdigi** [comment]
I guess? I'm not sure how to tell if the website is specifically instructing the browser to open the link in a new window.

If you're familiar with unraid..its the log files links of docker containers that is causing the issue.

**Comment by jlesage** [comment]
Ok I see.  Maybe you can try the solution explained here:
https://support.mozilla.org/en-US/questions/1193456

**Comment by angdigi** [comment]
Thank you! That worked.
