### ISSUE TITLE
[Feature request] how to get sound 

### ISSUE THREAD

**Issue by FreeL00P** [jlesage/docker-firefox#232]
youtube,x sound no work。

**Comment by jlesage** [comment]
Currently, sound support if very limited (https://github.com/jlesage/docker-firefox?tab=readme-ov-file#sound-support).  However, proper support is coming very soon.

**Comment by wody11** [comment]
> Currently, sound support if very limited (https://github.com/jlesage/docker-firefox?tab=readme-ov-file#sound-support). However, proper support is coming very soon.

Streaming audio from a server-based Docker container to a browser is quite challenging; I doubt it's feasible with your current setup, as this would require integrating WebRTC, which isn't just a simple feature addition. If you need assistance, feel free to contact wody911@gmail.com.

**Comment by jlesage** [comment]
Audio support has been added to the Docker image.
