### ISSUE TITLE
Can someone explain how to access the local file system via this browser?

### ISSUE THREAD

**Issue by ovizii** [jlesage/docker-firefox#26]
Basically, I am sitting in front of my workstation with a browser and am browsing to my docker-firefox browser and would like to upload a file buzt the upload mask only has accessto the "local" file system of the docker container. 

Is there a way to give it access to my workstation's fiel system? 

Hope I explained that in a way to convey the right question.

**Comment by paulo-maia** [comment]
same problem for downloading files :)

**Comment by jlesage** [comment]
Answered in issue https://github.com/jlesage/docker-firefox/issues/38.
