### ISSUE TITLE
[Feature request] Change title/descripter that appears in the Tab from host browser, i.e. currently is "Firefox"

### ISSUE THREAD

**Issue by yamikeigo** [jlesage/docker-firefox#272]
### Idea

sorry if this is possible already, I wasn't able to locate any documentation on it

basically, just looking for this option in order to differentiate between separate instances of this container running simultaneously

**Comment by yamikeigo** [comment]
answer found in #174

**Comment by jlesage** [comment]
There is currently no official way, but you can try as a hack to set the `APP_NAME` environment variable.

**Comment by yamikeigo** [comment]
that worked! thank you

**Comment by yamikeigo** [comment]
> There is currently no official way, but you can try as a hack to set the `APP_NAME` environment variable.

that worked! thank you
