### ISSUE TITLE
Where can I find the docker images with earlier versions of firefox?

### ISSUE THREAD

**Issue by famewolf** [jlesage/docker-firefox#28]
I'm wanting to use imacro's and the most recent versions no longer allow file access so I'd like to use an older version of firefox along with the associated older imacro's version.   Where can I see a list of these versions so I know the proper one to pull?

**Comment by jlesage** [comment]
Releases page ? https://github.com/jlesage/docker-firefox/releases

**Comment by famewolf** [comment]
Thanks.  That only goes back to v58 where I'd have to go to v52.  Guess I'll end up having to build an image myself.  Appreciate the response.
