### ISSUE TITLE
Widevine Plugin Support

### ISSUE THREAD

**Issue by mjd515** [jlesage/docker-firefox#29]
i am having issues using sites that use Widevine plugin. is there anyway to allow for this? i am open to mapping other volumes to the container to support this but i dont know which i should add or if the fix is elsewhere.

**Comment by jlesage** [comment]
Currently this plugin is not supported on Alpine Linux, because it is not open source and there is no `musl` compatible library available...

**Comment by mjd515** [comment]
i wont pretend i know what that last bit means lol. i understand not being able to implement seeing as its not open source. also im pretty sure it still wouldnt work for me because of sound support though the web page. thank you for responding! :)
