### ISSUE TITLE
How to add a font type?

### ISSUE THREAD

**Issue by winloud** [jlesage/docker-firefox#30]
I tried to change the firefox language to chinese simplified, but it didn't work well because less of chinese font in docker container.
How could I add a font into docker container?

**Comment by jlesage** [comment]
Did you try to set the `ENABLE_CJK_FONT` variable?
https://github.com/jlesage/docker-firefox#environment-variables

**Comment by jlesage** [comment]
Closing the issue.  Please re-open if needed.
