### ISSUE TITLE
Server disconnected (error : 1006) with nginx proxy manager

### ISSUE THREAD

**Issue by Laizrod** [jlesage/docker-firefox#31]
Hi.
So my issue is actually pretty difficult to explain.
I installed docker-firefox some days ago and everything was working perfectly. I was using nginx as reverse proxy in order to access firefox UI.
Then I decided today to use Nginx Proxy Manager instead of nginx itself. Everything is working flawlessly... except with your firefox and handbrake images.

So there's the problem.
This issue does not occur when firefox home page is the only page to be opened.
If i open any website with firefox (Google, or any website), then I stay inactive and I do not do anything on firefox for 3-4 mins, the web UI crashes and says "Server disconnected (code : 1006)".
Also, if I try the same thing locally (connecting to the UI with local IP, not thru nginx), the problem doesn't come out.
That's pretty weird because it does not occur on firefox home page; and I also get this problem with handbrake.
There's my nginx configuration for firefox, and a pic of the error.

![Capture d’écran 2019-11-09 à 22 30 31](https://user-images.githubusercontent.com/36924895/68535327-00d5f180-0341-11ea-8202-cdcd311a4325.png)
![Capture d’écran 2019-11-09 à 22 44 26](https://user-images.githubusercontent.com/36924895/68535403-85753f80-0342-11ea-938b-4dc3d5bda6d8.png)
![Capture d’écran 2019-11-09 à 22 30 44](https://user-images.githubusercontent.com/36924895/68535328-00d5f180-0341-11ea-8668-aba8350f74c7.png)
![Capture d’écran 2019-11-09 à 22 28 20](https://user-images.githubusercontent.com/36924895/68535329-00d5f180-0341-11ea-8d52-546b6d85516c.png)

I don't know if I have to post this issue in your github or if I had to post it in the Nginx Proxy Manager's but since I only get this problem with your images I decided to post it here.

**Comment by jlesage** [comment]
When the UI says "Server disconnected (code : 1006)", does a refresh of the page bring back the interface?

**Comment by Laizrod** [comment]
Yep.
But that’s a bit annoying to have to refresh and enter password again every 3-4 minutes :(

**Comment by jlesage** [comment]
Can you try to add `proxy_read_timeout 86400;` under the "Advanced" tab of your proxy host config?

**Comment by Laizrod** [comment]
My bad, I should have tried that earlier.
It worked.
Thank you :)

**Comment by myde2001** [comment]
Hi, the same is happening to me but I have the `proxy_read_timeout 86400;` line
