### ISSUE TITLE
Error for docker synology

### ISSUE THREAD

**Issue by Didier3L** [jlesage/docker-firefox#32]
The container does not want to run.
Error message

> Start container firefox failed OCI runtime create failed container with id exists

**Comment by jlesage** [comment]
Looks like the name of the container you are trying to create is already taken by another container...

**Comment by Didier3L** [comment]
error message

> Start container jlesage-firefox1 failed: {"message":"cgroups: cannot find cgroup mount destination: unknown"}.

**Comment by Didier3L** [comment]
[url=https://zupimages.net/viewer.php?id=19/46/ch7t.png][img]https://zupimages.net/up/19/46/ch7t.png[/img][/url]
[url=https://zupimages.net/viewer.php?id=19/46/ssuc.png][img]https://zupimages.net/up/19/46/ssuc.png[/img][/url]

**Comment by jlesage** [comment]
Did you set any memory/cpu limitation?

**Comment by bramus** [comment]
Works fine on Synology with DSM7. Looking at the screenshots, user is using DSM6.

On DSM6 most containers needs to be run with elevated privileges. On DSM7 this is not needed.

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
