### ISSUE TITLE
Permission errors on podman

### ISSUE THREAD

**Issue by kempy007** [jlesage/docker-firefox#34]
[root@localhost ~]# podman run --rm -it -p 5800:5800 --name=firefox -v /tmp/firefox:/config:z --shm-size 2g jlesage/firefox
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] check-snd.sh: executing...
[cont-init.d] check-snd.sh: sound not supported: device /dev/snd not exposed to the container.
[cont-init.d] check-snd.sh: exited 0.
[cont-init.d] firefox-set-prefs-from-env.sh: executing...
[cont-init.d] firefox-set-prefs-from-env.sh: exited 0.
[cont-init.d] firefox.sh: executing...
[cont-init.d] firefox.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise s6-fdholderd: warning: unable to spawn ./run - waiting 10 seconds
s6-svwait: fatal: timed out
[services.d] starting certsmonitor...
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise certsmonitor: warning: unable to spawn ./run - waiting 10 seconds
s6-svwait: fatal: timed out
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise s6-fdholderd: warning: unable to spawn ./run - waiting 10 seconds
[services.d] starting nginx...
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise nginx: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise certsmonitor: warning: unable to spawn ./run - waiting 10 seconds
s6-svwait: fatal: timed out
[services.d] starting xvfb...
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise xvfb: warning: unable to spawn ./run - waiting 10 seconds
^Cs6-svscan: warning: unable to spawn .s6-svscan/SIGINT: Permission denied
^Cs6-svscan: warning: unable to spawn .s6-svscan/SIGINT: Permission denied
^Cs6-svscan: warning: unable to spawn .s6-svscan/SIGINT: Permission denied
^Cs6-svscan: warning: unable to spawn .s6-svscan/SIGINT: Permission denied

**Comment by jlesage** [comment]
I'm not familiar with podman, but it seems that some permissions are not granted properly.  Can you run with the `--privileged` option to see if it makes any difference?

**Comment by kempy007** [comment]
Sorry for long delay, but that did not work. 

I guess podman is incompatible since it runs in userspace under CRI-O instead.

**Comment by egvimo** [comment]
For me it worked with `:Z` instead of `:z` or `:rw`.

See https://github.com/containers/podman/issues/3683
