### ISSUE TITLE
IPSec VPN

### ISSUE THREAD

**Issue by paulo-maia** [jlesage/docker-firefox#36]
Hi, any idea on how to run this on top of an IPSec connection?

**Comment by paulo-maia** [comment]
stupid question I guess, closed.

**Comment by pcbuildpluscoding** [comment]
@paulo-maia I published this container through a remote URL via a wireguard VPN that streams the container's websocket connection. Checkout [this youtube clip](https://www.youtube.com/watch?v=bVKNSf1p1d0)
