### ISSUE TITLE
Possible to open tabs from docker shell?

### ISSUE THREAD

**Issue by travisjayday** [jlesage/docker-firefox#46]
Hi, is it possible to open a tab from the docker shell? In a regular environment running `firefox google.com` would open a new tab in the current instance of firefox but that doesnt seem to work :(

**Comment by jlesage** [comment]
This should work:

```
HOME=/config s6-applyuidgid -u $USER_ID -g $GROUP_ID /usr/bin/firefox --profile /config/profile -new-tab www.google.com
```

**Comment by travisjayday** [comment]
Thanks that works like a charm!
