### ISSUE TITLE
Fullscreen toggle on the navigation bar

### ISSUE THREAD

**Issue by JZ-SmartThings** [jlesage/docker-firefox#49]
Hi, thank you for this awesome container... it works very well on old iPads and allows me to use newer sites like Home Assistant and Polymer which is NOT supported on iOS 9.3.5 anymore.

I have an enhancement if possible: pressing the hamburger inside of the container's Firefox and next to the zoom buttons there's a full-screen (F11) button. Once you click that, it's impossible to click F11 on an iPad and I have to go to a computer to get it out of Firefox's full-screen mode. Would it be possible to have an F11 button in the navigation bar?

All the best!

**Comment by jlesage** [comment]
I would recommend installing an extension like https://addons.mozilla.org/en-US/firefox/addon/toggle-fullscreen/, which allows you to easily exit fullscreen mode by right-clicking into the web page.

**Comment by JZ-SmartThings** [comment]
Interesting, I tried it and it only added a button on top of the toolbar which worked to get to full-screen but right-click on the page did not return it back to normal view. Which OS are you using with Firefox on in order for right-click to behave in that manner?

To be honest right-click is not really available on an older iPad... would you mind sharing/explaining a bit on where the top toolbar comes from? Is that your code or part of some Firefox release that you're baking into this container? I'm pretty crafty and tried to make sense of it by looking at the source but it doesn't seem like what I'm asking for is hackable in your container but rather that FF release instead. Please point me to that FF release as I've never seen FF offered in any other way except GUI.

**Comment by jlesage** [comment]
> Interesting, I tried it and it only added a button on top of the toolbar which worked to get to full-screen but right-click on the page did not return it back to normal view. Which OS are you using with Firefox on in order for right-click to behave in that manner?

When you right click in the page, a context menu appears, in which you have to option to exit full screen.  On the iPad, you should be able to right click by performing a long press.

> To be honest right-click is not really available on an older iPad... would you mind sharing/explaining a bit on where the top toolbar comes from? Is that your code or part of some Firefox release that you're baking into this container? I'm pretty crafty and tried to make sense of it by looking at the source but it doesn't seem like what I'm asking for is hackable in your container but rather that FF release instead. Please point me to that FF release as I've never seen FF offered in any other way except GUI.

The top toolbar is not part of the Firefox release.  A standard Firefox instance is running inside the container and its UI is accessible via VNC using an HTML VNC client.  The top toolbar is part of this VNC client.

**Comment by JZ-SmartThings** [comment]
You're absolutely right, thanks for your awesome work! Now I see that it's basically the VNC doing all the work (hence the 2 port numbers in hind-sight). I miss that old toy :) closing this one out with Toggle Fullscreen working as expected with right-click accessible via long tap on a tablet.
