### ISSUE TITLE
secure login before firefox start

### ISSUE THREAD

**Issue by Fabeuss** [jlesage/docker-firefox#55]
I don't know if it's really an issue but as I use this container with a reverse proxy (at work), I wanted to know if it's possible to secure the access with login and password...
Indeed, if I leave the container as it is, anyone can access to "my" firefox via the url, it's not very "safe"...?

Thanks

**Comment by jlesage** [comment]
I guess this could be achieved by your reverse proxy ?  Which one are you using ?

**Comment by Fabeuss** [comment]
The one integrated on DSM Synology...

**Comment by jlesage** [comment]
You could set a VNC password (https://github.com/jlesage/docker-firefox#vnc-password), but that's not very secure (password only, limited to 8 characters).
If the reverse proxy integrated in Synology doesn't allow you to set a username/password, I would recommend that you try to use another one.

**Comment by Fabeuss** [comment]
Ok thanks, i will try vnc pwd...

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
