### ISSUE TITLE
v1.12.0 seems to be crashing all the time

### ISSUE THREAD

**Issue by jrdoublet** [jlesage/docker-firefox#56]
Hi,
I run 2 firefox containers, one with v1.11.0 and one with v1.12.0 
my docker compose files are exactly the same except the version

v1.12 crashes all the time
v1.11 is fine

here's my docker compose file :

# Firefox - Web Browser
  firefox-vpn:
    image: jlesage/firefox:v1.11.0
#    image: jlesage/firefox:latest
    container_name: firefox
    restart: unless-stopped
    network: traefik
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/firefox:/config
      - /dev/shm:/dev/shm
      - $USERDIR/shared_data:/shared
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      VNC_PASSWD: $FIREFOX_VNC_PASSWD
    labels:
      - "traefik.enable=true"
      ## traefik conf....

**Comment by jlesage** [comment]
What do you mean exactly by "is crashing"?  Firefox doesn't start ?  Could you provide the container's log ?

**Comment by alexsahka** [comment]
My is crashed as well.
![image](https://user-images.githubusercontent.com/7469537/85810030-98405700-b70e-11ea-9b18-7cf9af27ac5e.png)

**Comment by jlesage** [comment]
@alexsahka, you seem to have a different issue.  Did you set the `--shm-size` parameter ?
https://github.com/jlesage/docker-firefox#increasing-shared-memory-size

**Comment by M1K3Yio** [comment]
I am also seeing this in the latest, my tabs keep randomly crashing. I also already had the --shm-size 2g.  I am running the Docker container on my unraid.  v1.11 worked perfectly fine.

**Comment by jrdoublet** [comment]
I'm sorry, I couldn't find the logs, could you please help me ?

**Comment by jrdoublet** [comment]
ok I think I found the logs 

I've seen two messages : 

- 1st one in nginx/error.log :
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Failed buffer for 0, 0, 1600, 885 (t=233447) [GFX1-]: Failed buffer for 0, 0, 1600, 885

- 2nd one in firefox/error.log : 

###!!! [Parent][MessageChannel] Error: (msgtype=0x380035,name=PContent::Msg_UpdateSharedData) Channel error: cannot send/recv

[Parent 6237, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/buildozer/aports/community/firefox/src/firefox-77.0.1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
[Parent 6237, Gecko_IOThread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/buildozer/aports/community/firefox/src/firefox-77.0.1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
[Parent 6237, Gecko_IOThread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /home/buildozer/aports/community/firefox/src/firefox-77.0.1/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
Gdk-Message: 10:12:44.953: firefox: Fatal IO error 0 (No error information) on X server :0.


I hope this helps

**Comment by jlesage** [comment]
The tab crash seems related to a system call not allowed by default by Docker.  This particular system call (`membarrier`) will be whitelisted in the next Docker version.

For now, a quick workaround is to create the container with the following option:
```
--security-opt seccomp=unconfined
```
I will provide more details on the issue and the possible workarounds in the documentation.
