### ISSUE TITLE
Download Folder

### ISSUE THREAD

**Issue by capriciousduck** [jlesage/docker-firefox#57]
How do I download to a folder I mounted while creating the docker container? I did put "rw" at the end of the volume binding line. But I am not able to save in the mounted directory. 

Here is my docker command.

`docker run -d --restart unless-stopped \
    --name=firefox \
    -p 5001:5800 \
    -p 5000:5900 \
    -v firefox_config:/config:rw \
 -v /mnt/systemdisk/firefox:/mnt/systemdisk/firefox:rw \
 -e KEEP_APP_RUNNING=1 \
 -e DISPLAY_WIDTH=1920 \
 -e DISPLAY_HEIGHT=1080 \
    --shm-size 2g \
jlesage/firefox:v1.11.0`

**Comment by jlesage** [comment]
I would check the permissions/ownership of `/mnt/systemdisk/firefox`.  Maybe you need to adjust `USER_ID` and `GROUP_ID` ?

**Comment by capriciousduck** [comment]
Ok, I'll check that.

I was trying to upload a 23Gb zip file to [Notion.so](https://notion.so) website. I have an account at that site. The file was in the default download folder. However, when I initiate the upload, the upload failed. But when I try the same thing on my PC, the upload is working as it should.

**Comment by capriciousduck** [comment]
> I would check the permissions/ownership of `/mnt/systemdisk/firefox`. Maybe you need to adjust `USER_ID` and `GROUP_ID` ?

This one worked.

**Comment by jlesage** [comment]
Perfect.  I'm closing this issue.
