### ISSUE TITLE
Unable to set firefox preferences via ENV

### ISSUE THREAD

**Issue by lewistham9x** [jlesage/docker-firefox#59]
I've been trying to set up the browser such that it functions as a private browser, using this variable: browser.privatebrowsing.autostart

I've tried FF_PREF_BROWSER_PRIVATEBROWSING_AUTOSTART=TRUE , FF_PREF_BROWSER.PRIVATEBROWSING.AUTOSTART=TRUE, and BROWSER.PRIVATEBROWSING.AUTOSTART=TRUE

but none of these environment variables seem to trigger the script that enables this setting in Firefox.

**Comment by jlesage** [comment]
You should try using something like this:
```
FF_PREF_PRIVATE_BROWSING=browser.privatebrowsing.autostart=true
```

**Comment by lewistham9x** [comment]
Alright, thanks a lot! Should have been more thorough.
