### ISSUE TITLE
Firefox requires the membarrier system call

### ISSUE THREAD

**Issue by JulyIghor** [jlesage/docker-firefox#64]
Getting this error for every tab
![image](https://user-images.githubusercontent.com/3390357/92471453-4325c480-f1d8-11ea-9558-f451bbc01dc6.png)

**Comment by jlesage** [comment]
Yes, instructions are provided here: https://github.com/jlesage/docker-firefox#allowing-the-membarrier-system-call
Let met know if you still have problems after that.

**Comment by JulyIghor** [comment]
Thanks, it is working

**Comment by MilesTEG1** [comment]
Hello,
Is there a way to implement it using a docker-compose file ?
I don't find any lead on that... And I create my container using a docker-compose.yml file with Portainer CE v2.1.1.
Thanks in advance.

**Comment by jlesage** [comment]
You can add something like this:
```
    security_opt:
      - seccomp:unconfined
```
Or you can update your Docker.  The membarrier system call is not a problem with recent versions of Docker.
