### ISSUE TITLE
no vnc connection to docker on windows

### ISSUE THREAD

**Issue by 2andr** [jlesage/docker-firefox#65]
Thanks for great work.
i have installed docker-firefox in docker-desktop on Win 10 
Web version of firefox work fine (http://my_host_ip:5800)

But i cant connect to vnc :(  ( my_host_ip:5900 )
Any vnc clients (from same machine, from tablets) cant connect.

In docker console i see:
`12/09/2020 13:59:53 Listening for VNC connections on TCP port 5900
.................
12/09/2020 13:59:53 screen setup finished.

12/09/2020 13:59:53
The VNC desktop is: 2b3b2628a6fa:0

PORT=5900`
Port 5900 In Windows Firewall opened

Can you help me?

**Comment by jlesage** [comment]
How did you created your container (what is your `docker run` command)?  Did you exposed port 5900 (`-p 5900:5900`)?

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
