### ISSUE TITLE
Crash loop when mapping /dev/shm in Synology docker

### ISSUE THREAD

**Issue by frederiktoft** [jlesage/docker-firefox#66]
I'm having the shared memory issue with running Firefox in Docker on Synology, using their own Docker application. I have tried to configure Firefox to use memory as cache and then setting the dockers ram to 4gb but to see if that could work around it.
Using "--shm-size 2g" as the execution command crashes the container itself, if I make it precede after "/init" which makes the execution command "/init --shm-size 2g". 
So I have tried to map the volume /dev/shm instead. But that causes an endless crash boot loop for the application itself. The vnc screen is black and the log just says it tries to start Firefox over and over again. It's strange because the /config mapping works just fine. I have also tried to run the container as an elevated user but still the same.

I am using the latest version as of writing.

**Comment by jlesage** [comment]
I don't have a Synology to play with, but according to https://github.com/jlesage/docker-firefox/issues/16, it seems that this parameter cannot be set via the UI.

**Comment by kos9090** [comment]
The solution is to SSH (enable first) into the Synology, then get yourself su rights. Then run all the commands in the shell. If you experience binding errors alter the paths in the Synology Docker GUI afterwards by removing and setting them again.

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
