### ISSUE TITLE
Chinese display error on website

### ISSUE THREAD

**Issue by leftvalue** [jlesage/docker-firefox#68]
![WX20200923-130452](https://user-images.githubusercontent.com/19648340/93969302-2a9fd780-fd9e-11ea-9b9b-d9c4b16d4d8e.png)
hi,it seems that the docker doesn't have the font?so that chinese cannot display normally.how can i fix it?thanks~

**Comment by leftvalue** [comment]
ok,i have found a way to fix it.
just copy all fonts file of windows7 to /usr/share/fonts
execute
```bash
 mkfontscale
 mkfontdir
 fc-cache   
```
then it succeed
![image](https://user-images.githubusercontent.com/19648340/93970924-a51e2680-fda1-11ea-8d5b-7c3327c72343.png)

perhaps we can offer a choice for docker user,if set ,download fonts automate?

**Comment by jlesage** [comment]
Setting the `ENABLE_CJK_FONT` environment variable should do the trick.  See https://github.com/jlesage/docker-firefox#environment-variables.

**Comment by leftvalue** [comment]
> Setting the `ENABLE_CJK_FONT` environment variable should do the trick. See https://github.com/jlesage/docker-firefox#environment-variables.

that's very nice of you.thanks 🌈
