### ISSUE TITLE
Pop ups not handled well

### ISSUE THREAD

**Issue by rix1337** [jlesage/docker-firefox#69]
Hi @jlesage and thanks for your awesome stream of VNC-enabled containers.

This issue is regarding the missing application menu bar (with min, max and close buttons) -> these do not need to exist for the main window.
I am regularly using a web application that opens a small pop-up (200x50 px) that goes into exclusive full screen and cannot be closed without force closing / restarting firefox entirely.

I am using this as a baseimage for a custom build, so a hint what to change will be enough for me to fix it myself.

Just try:
http://www.popuptest.com/popuptest1.html
(you have to allow the popups)

Native desktop browser on windows:
![grafik](https://user-images.githubusercontent.com/9930448/95084115-b9591080-071d-11eb-884d-287bce02c944.png)

The issue:
![grafik](https://user-images.githubusercontent.com/9930448/95084062-a7776d80-071d-11eb-8871-b0046d40048f.png)

Is there any way to prevent this from happening?

**Comment by jlesage** [comment]
I would recommend to install the following extension: https://add0n.com/single-window.html

**Comment by rix1337** [comment]
I have tested this and it works like a charm. Thank you!
