### ISSUE TITLE
Un able to open http://192.168.1.xx:5800

### ISSUE THREAD

**Issue by Christianb233** [jlesage/docker-firefox#71]
Hello @jlesage
Fisrt of all, I Thanks you for this github which could help me to see Home Assistant into an old IPAD IOS 9.3.5
I am unfortunately beginner in docker.
So I have just used the Quick start "docker run..." that you propose.
This seems to work well. But when I open a web browser with my http://192.168.1.xx:5800 it doesn't open anything.
As I have Also installed portainer on Home Assistant, I am able to say that a container has been created but not started. When I Try to start it, it quickly starts the stops running, when I come to the log I see this error message
Standard_init_linux.go:211: exec user process caused "exec format error"
And I don't KNow how to solve this issue :-( can you help me please ?

**Comment by jlesage** [comment]
Currently this containers run only on x68_64 CPU.  Looks like you are using a different platform ?

**Comment by Christianb233** [comment]
Hello, thank you for your answer : I try to install this container on a raspberry pi 4. It is strange because I have read from another post about home assistant that someone has succeeded to install this container on a raspberry pi3b+ 🤔

**Comment by jlesage** [comment]
Humm it's probably not this same container...  Support for other platforms is coming, but is not there yet.

**Comment by jlesage** [comment]
Latest image is now multi-arch.
