### ISSUE TITLE
Can i Copy each other  by VNC viewer or other tools

### ISSUE THREAD

**Issue by c3peng** [jlesage/docker-firefox#74]
When i use VNC Viewer to connect the container，i can copy from my PC to the firefox but can't copy from firefox to my PC.
Is there some way copy from firefox to my PC?

**Comment by jlesage** [comment]
It should work... Did you try to copy with ctrl+c and/or right click->copy ?
Did you try using the web interface ?

**Comment by c3peng** [comment]
I have try both VNC Viewer and web interface. I can copy from my PC or MAC to firefox,but can't from firefox to my PC or MAC.

**Comment by jlesage** [comment]
It seems to works fine for me using the web UI under Safari: I select some text, hit ctrl+v or right click -> Copy.  Then, when I click the big Clipboard button, I see what I've copied.

**Comment by c3peng** [comment]
it's my mistake.
When i change "ServerCutText" from false to true in VNC Viewer,it works.
thank you.
