### ISSUE TITLE
alltime crashing tabs - docker 20.10.1

### ISSUE THREAD

**Issue by ananchev** [jlesage/docker-firefox#77]
Running on ubuntu xenial with the very basic docker-run getting started example. Tabs are all time crashing.
Tried the described fixes about membarrier as well as pulling two older image versions, but all time same. 
There is a warning & error message repeating in firefox error.log (see below). Nothing in nginx. 
 

> [Parent 986, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: fi
le /home/buildozer/aports/community/firefox/src/firefox-81.0/ipc/chromium/src/chrome/common/fi
le_descriptor_set_posix.cc, line 19

> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0x390038,name=PContent::Msg_UpdateSharedData)
> Channel error: cannot send/recv

[error.log](https://github.com/jlesage/docker-firefox/files/5754676/error.log)

**Comment by ananchev** [comment]
The issue seems to be platform related: I made a test on another box running Arch: there all works just as it should. 
Could you please advise how to troubleshoot?

**Comment by jlesage** [comment]
Looks like issue https://github.com/jlesage/docker-firefox/issues/62.

Did you check that Ubuntu is up-to-date, especially the kernel ?

**Comment by ananchev** [comment]
Thanks Jocelyn! 
Indeed kernel related and is now fixed. Was running still on 4.4 (4.4.0-197), now updated to 4.15.0-128 and no tabs crashing anymore.

**Comment by jlesage** [comment]
Great, thanks for the follow up.  I will add a note about this in the documentation.

**Comment by JeremyMordkoff** [comment]
also confirmed 4.13 does not work, 4.15 does work
