### ISSUE TITLE
Question: How does docker-firefox get the version upgrades ? manual or automatic?

### ISSUE THREAD

**Issue by W-M-B** [jlesage/docker-firefox#78]
Hello,
I love the firefox container, solves a nagging problem for my!
my questions which I didnt understand after reading the the manual:
How do version upgrade from firefox work? 
Does it update like on a local windows installation ? (I guess not)
how do I perform updates, then? 
After the explanation I would be happy to add this to the manual :)
Regards, Wolfram

**Comment by jlesage** [comment]
Firefox doesn't update itself automatically.  To get a Firefox update, the container image needs to be updated (https://github.com/jlesage/docker-firefox#docker-image-update).

**Comment by W-M-B** [comment]
thank you!
