### ISSUE TITLE
Only navigation bar (+loading circle) visible via web access - local access works

### ISSUE THREAD

**Issue by kos9090** [jlesage/docker-firefox#80]
Hello again, if I access the container via its 192xxxx:5800 URL it works perfect.

Now, If i come there via reverse proxy from the internet, I can only see the title bar and the loading circle. I tried many different browsers, even on mobile phones. No changes.  

I'm running the container on a Synology - **Any suggestions?** 

![Bildschirmfoto 2021-01-12 um 23 04 37](https://user-images.githubusercontent.com/77353558/104380186-ec841a80-552a-11eb-9dc4-bfcd41b58554.png)

**Comment by kos9090** [comment]
Ok I should stop writing issues 5 min before I find solutions. I hope this helps somebody:

This to be added to the Reverse Proxy settings in DSM.

![Bildschirmfoto 2021-01-12 um 23 29 28](https://user-images.githubusercontent.com/77353558/104382264-1854cf80-552e-11eb-995c-9d18c3ce536d.png)

**Comment by vomidug** [comment]
Facing the same issue inside of docker+compose with an nginx as a server
![image](https://user-images.githubusercontent.com/38423889/120655848-be788600-c48b-11eb-9017-f433ac648f41.png)
It leads to 
![image](https://user-images.githubusercontent.com/38423889/120656257-2333e080-c48c-11eb-951a-5e7e5c4d184d.png)

If I comment out the /websockify section and set it like this 
![image](https://user-images.githubusercontent.com/38423889/120656687-8160c380-c48c-11eb-880f-cfab3c27d8c8.png)

It loads something for a long time and shows the same error again

Thanks in advance. If it is needed - I can raise a new issue

**Comment by vomidug** [comment]
Well, yeah, it doesn't reopen it...
