### ISSUE TITLE
how to build firefox for raspberry pi4 platform

### ISSUE THREAD

**Issue by ayukhno** [jlesage/docker-firefox#81]
Hi everybody, 
i've tried to find out with a way how to build firefox under RPI4 platform but sorry didn't find. i would appreciate for your help to shoe me a way how to do it. thanks in advance 
alex y.

**Comment by jlesage** [comment]
Support for architectures other than x86_64 is not ready yet.  I'm working on that...

**Comment by Gan2020** [comment]
Will wait. Thanks

**Comment by krswin** [comment]
@jlesage thanks for your great work. Is there any date when it will available for Raspberry Pi  3/4? thanks

**Comment by rssindian** [comment]
Hi @jlesage ,thank you for your awesome work on this container, this is a really helpful tool. I would also like to request you to extend the support for ArmV7/Raspberry Pi, I tried playing around with docker buildx multiarch support, but no luck. I am guessing it would be straight forward for you!

**Comment by yukselgunal** [comment]
@jlesage Any plans to support the s390x architecture?

**Comment by jlesage** [comment]
Latest image is now multi-arch.
