### ISSUE TITLE
Internal PORT Change

### ISSUE THREAD

**Issue by capriciousduck** [jlesage/docker-firefox#82]
Is it possible to change the internal listening port(5080)? I am trying to run firefox on a PaaS and they require the app to run on port 8080, not on any other port. Also, in any way, is it possible to pass $PORT variable?

**Comment by jlesage** [comment]
This is currently not possible.  However, if you are using the default bridge network, you can map port 5800 to any one on the host.

**Comment by capriciousduck** [comment]
All right. Closing the issue.

**Comment by capriciousduck** [comment]
Is it possible if I clone the repo and make the changes? If yes, do I have to pull the baseimage docker image and change the port there?

**Comment by jlesage** [comment]
Yes, the ports are defined in the baseimage.

**Comment by jlesage** [comment]
This is now supported with latest image.
