### ISSUE TITLE
VNC_PASSWORD 

### ISSUE THREAD

**Issue by hangon1234** [jlesage/docker-firefox#86]
Thank you so much for your great project.

https://github.com/jlesage/docker-firefox#vnc-password

VNC_PASSWORD variable not working.
However, make .vncpass_clear works well.

My docker composer file looks like this
![image](https://user-images.githubusercontent.com/34829852/109544141-8d925900-7b0a-11eb-9784-65d679ecf602.png)

not work.

when I make .vncpass_clear file
![image](https://user-images.githubusercontent.com/34829852/109544407-e06c1080-7b0a-11eb-8018-746c6c93baed.png)

works well.

Thank you so much for your help.

**Comment by jlesage** [comment]
To verify that the variable is properly set, can you provide the output of `docker inspect <container name>` ?

**Comment by hangon1234** [comment]
> To verify that the variable is properly set, can you provide the output of `docker inspect <container name>` ?

emmmm.......???? 
try after sleeping, it works well 😭
maybe I make mistake last night.

``"Env": [
    "VNC_PASSWORD="test",
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "LANG=en_US.UTF-8",
    "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
    "S6_SERVICE_DEPS=1",
    "USER_ID=1000",
    "GROUP_ID=1000",
    "APP_NAME=Firefox",
    "APP_USER=app",
    "XDG_DATA_HOME=/config/xdg/data",
    "XDG_CONFIG_HOME=/config/xdg/config",
    "XDG_CACHE_HOME=/config/xdg/cache",
    "XDG_RUNTIME_DIR=/tmp/run/user/app",
    "DISPLAY=:0",
    "DISPLAY_WIDTH=1280",
    "DISPLAY_HEIGHT=768"
],
``

I found that make new session (private browse tab) also required to see password form.
Thank you so much. I will close this issue.
