### ISSUE TITLE
SHM Size

### ISSUE THREAD

**Issue by capriciousduck** [jlesage/docker-firefox#88]
How to use /tmp for shm instead of /dev/shm? I am trying to run firefox on a PaaS and I don't have the ability to pass --shm-size parameter while deploying the app.

**Comment by jlesage** [comment]
To my knowledge, Firefox doesn't allow disabling usage of `/dev/shm`.
However, maybe you can try to add it as a volume instead (` -v /dev/shm:/dev/shm`)?

**Comment by jlesage** [comment]
Did the volume mapping worked ?

**Comment by capriciousduck** [comment]
Well, I can't say as the PaaS I'm hosting firefox on don't allow me to either change the shm size or to mount volumes.
