### ISSUE TITLE
Synology : Server disconnected (code 1006)

### ISSUE THREAD

**Issue by hot22shot** [jlesage/docker-firefox#9]
Hello,

I'm getting the error : server disconnected (code 1006).
From googling I suppose this is not purely related to docker-firefox but I can't find what is wrong with my configuration.

The docker is installed on my Synology and reached through the embedded nginx of the NAS.
I try to reach it from a subdomain configured to reach the port 5800 of the docker image.

The session starts (I can see the navbar) but after a while I get this error.

Here's some log from the docker image :
10/12/2018 10:12:13 Got connection from client 127.0.0.1
10/12/2018 10:12:13   other clients:
10/12/2018 10:12:13 Got 'ws' WebSockets handshake
10/12/2018 10:12:13 Got protocol: binary
10/12/2018 10:12:13   - webSocketsHandshake: using binary/raw encoding
10/12/2018 10:12:13   - WebSockets client version hybi-13
10/12/2018 10:12:13 Disabled X server key autorepeat.
10/12/2018 10:12:13   to force back on run: 'xset r on' (3 times)
10/12/2018 10:12:13 incr accepted_client=7 for 127.0.0.1:60684  sock=10
10/12/2018 10:12:13 created   xdamage object: 0x600031
10/12/2018 10:13:13 rfbProcessClientProtocolVersion: client gone
10/12/2018 10:13:13 client_count: 0
10/12/2018 10:13:13 Restored X server key autorepeat to: 1
10/12/2018 10:13:13 Client 127.0.0.1 gone
10/12/2018 10:13:13 Statistics             events    Transmit/ RawEquiv ( saved)
10/12/2018 10:13:13  TOTALS              :      0 |         0/        0 (  0.0%)
10/12/2018 10:13:13 Statistics             events    Received/ RawEquiv ( saved)
10/12/2018 10:13:13  TOTALS              :      0 |         0/        0 (  0.0%)
10/12/2018 10:13:16 destroyed xdamage object: 0x600031

Regards

**Comment by hot22shot** [comment]
Ok, probem solved, WebSocket was not activated on NGINX.
Once configured it works !

Cheers

**Comment by pudding1009** [comment]
Hello,

could you explain more how did you fix that problem ?
I'm trying to use it but same error with the same configuration...

Thanks !

**Comment by jlesage** [comment]
You have issue with your reverse proxy?  Did you see https://github.com/jlesage/docker-firefox#reverse-proxy ?

**Comment by pudding1009** [comment]
Hello. 

I solved the problem with WebSocket activation on the Synology reverse proxy conf. 
All is fine, thanks a lot !
But sometime, I have (after navigate) error « server disconnected (code : 1006)... dont known why...

**Comment by jlesage** [comment]
This is often fixed by clearing your browser's cache.

**Comment by pudding1009** [comment]
Ok, I tried but always the same error...

**Comment by jlesage** [comment]
Is it working without going through the reverse proxy?  If yes, then it seems that you still have an issue with the WebSocket.
You can also open the browser's developper tools and looks at the console for errors.  You will probably see that the WebSocket connection fails.

**Comment by pudding1009** [comment]
actually without going through the reverse proxy, I do not have the error 1006 ...
To give more details, by the reverse proxy, the error arrives after a few minutes without activity....

Here is the console message : 
util.js:218  Msg: Password Required
Util.Warn @ util.js:218
Util.Warn @ util.js:218
2util.js:218  Msg: Authentication OK
Util.Warn @ util.js:218
util.js:218  Msg: Connected (encrypted) to: Firefox
Util.Warn @ util.js:218
util.js:218 WebSocket on-close event
Util.Warn @ util.js:218
util.js:220  Msg: Server disconnected (code: 1006)
Util.Error @ util.js:220

Don't known if this could be util ?

**Comment by pudding1009** [comment]
More details on error, from console of FireFox.
Test method :
 - open a FF navigator
 - go to my personnal link "https://web.mydomain.fr" (where reverse proxy link to "localhost:5800")
 - waiting 50-60s
 - then error 1006 appear

https://www.noelshack.com/2019-12-2-1552986895-error-1006.png

Starting UI...  novnc-ui.min.js:1:3611
 Msg: noVNC ready: native WebSockets, canvas rendering  novnc-core.min.js:1:2452
  novnc-core.min.js:1:2452
GET 
https://web.mydomain.fr/websockify [HTTP/1.1 407 Proxy Authentication Required 14 ms]
 Msg: Starting VNC handshake  novnc-core.min.js:1:2452
 Msg: Sent ProtocolVersion: 003.008  novnc-core.min.js:1:2452
 Msg: Authenticating using scheme: 2  novnc-core.min.js:1:2452
 Msg: Password Required  novnc-core.min.js:1:2452
  novnc-core.min.js:1:2452
 Msg: Authentication OK novnc-core.min.js:1:2452
 Msg: Connected (encrypted) to: Firefox  novnc-core.min.js:1:2452
WebSocket on-close event  novnc-core.min.js:1:2452
 Msg: Server disconnected (code: 1006)  novnc-core.min.js:1:2504
	Util.init_logging/Util.Error https://web.mydomain.fr/js/novnc-core.min.js:1:2504
	<anonyme> https://web.mydomain.fr/js/novnc-core.min.js:1:72736
	<anonyme> https://web.mydomain.fr/js/novnc-core.min.js:1:73735
	RFB/< https://web.mydomain.fr/js/novnc-core.min.js:1:68502
	Websock.prototype.open/this._websocket.onclose< https://web.mydomain.fr/js/novnc-core.min.js:1:21394
Error while connected.  novnc-core.min.js:1:2504
	Util.init_logging/Util.Error https://web.mydomain.fr/js/novnc-core.min.js:1:2504
	<anonyme> https://web.mydomain.fr/js/novnc-core.min.js:1:73453
	<anonyme> https://web.mydomain.fr/js/novnc-core.min.js:1:73735
	RFB/< https://web.mydomain.fr/js/novnc-core.min.js:1:68502
	Websock.prototype.open/this._websocket.onclose< https://web.mydomain.fr/js/novnc-core.min.js:1:21394

**Comment by pudding1009** [comment]
OK ! After reading this thread : https://github.com/novnc/noVNC/issues/567
and particulary this post :
 karinepires commented Jun 7, 2016

Hello all,
I was having the same issue in my application and decided to follow this issue just in case.
I finally managed to solve it with a different strategy.
So, to complete what @Ziris85 said, if you are using nginx as a proxy to your websocketify connection you may want to complete the configuration with different timeouts.
For example one can add the following code to the nginx configuration on the proxied block to increase the timeout to 1hour:

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

I think my problem was a timer set in reverse proxy, so I looking for in Synology parameters and I found this : (sorry for the UI in french)
[url=https://www.noelshack.com/2019-12-2-1553001309-reverseproxy-syno-param.png][img]https://image.noelshack.com/minis/2019/12/2/1553001309-reverseproxy-syno-param.png[/img][/url]

Initially, params was set to 60s, with new values to 3600s, all is fine !
Thanks a lot for your help !
