### ISSUE TITLE
[Feature Request] Open page given an URL Environment Var

### ISSUE THREAD

**Issue by Hattshire** [jlesage/docker-firefox#92]
Ease of ~~open-that-quick~~ use
```
docker run -d \
    --name=firefox \
    -p 5800:5800 \
    -v /docker/appdata/firefox:/config:rw \
    --shm-size 2g \
    -e URL="https://exam.pl/e" \
    jlesage/firefox
```

**Comment by penggwu** [comment]
There is no Environment Var named URL. Maybe you can set homepage by [Setting Firefox Preferences Via Environment Variables](https://github.com/jlesage/docker-firefox#setting-firefox-preferences-via-environment-variables) to open the URL.

**Comment by Hattshire** [comment]
> There is no Environment Var named URL. Maybe you can set homepage by [Setting Firefox Preferences Via Environment Variables](https://github.com/jlesage/docker-firefox#setting-firefox-preferences-via-environment-variables) to open the URL.

That's what I wanted, I know there's no `URL` eVar, and `-e "FF_PREF_HOME=browser.startup.homepage=\"https://duckduckgo.com\""` is somewhat ugly.

So, changed the title for clarity.

**Comment by jlesage** [comment]
Implemented in latest image.
