### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by nzeminski** [jlesage/docker-firefox#94]
Hi,
I am experiencing random crashes. I will attach the screen shot I see, logs and my docker create command that I am using.
![image](https://user-images.githubusercontent.com/60979973/119362841-24d6fa80-bc7b-11eb-9a93-143fafadb1b1.png)

Output from "docker logs firefox"
Mozilla Firefox 84.0.2
24/05/2021 10:24:37 Got connection from client 127.0.0.1
24/05/2021 10:24:37   other clients:
24/05/2021 10:24:37 Got 'ws' WebSockets handshake
24/05/2021 10:24:37 Got protocol: binary
24/05/2021 10:24:37   - webSocketsHandshake: using binary/raw encoding
24/05/2021 10:24:37   - WebSockets client version hybi-13
24/05/2021 10:24:37 Disabled X server key autorepeat.
24/05/2021 10:24:37   to force back on run: 'xset r on' (3 times)
24/05/2021 10:24:37 incr accepted_client=1 for 127.0.0.1:37902  sock=10
24/05/2021 10:24:37 Client Protocol Version 3.8
24/05/2021 10:24:37 Protocol version sent 3.8, using 3.8
24/05/2021 10:24:37 rfbProcessClientSecurityType: executing handler for type 1
24/05/2021 10:24:37 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
24/05/2021 10:24:37 Pixel format for client 127.0.0.1:
24/05/2021 10:24:37   32 bpp, depth 24, little endian
24/05/2021 10:24:37   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
24/05/2021 10:24:37 no translation needed
24/05/2021 10:24:37 Enabling NewFBSize protocol extension for client 127.0.0.1
24/05/2021 10:24:37 Using image quality level 6 for client 127.0.0.1
24/05/2021 10:24:37 Using JPEG subsampling 0, Q79 for client 127.0.0.1
24/05/2021 10:24:37 Using compression level 9 for client 127.0.0.1
24/05/2021 10:24:37 Enabling LastRect protocol extension for client 127.0.0.1
24/05/2021 10:24:37 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
24/05/2021 10:24:37 Using tight encoding for client 127.0.0.1
24/05/2021 10:24:37 client 1 network rate 503.1 KB/sec (30530.0 eff KB/sec)
24/05/2021 10:24:37 client 1 latency:  49.1 ms
24/05/2021 10:24:37 dt1: 0.0103, dt2: 0.1971 dt3: 0.0491 bytes: 91972
24/05/2021 10:24:37 link_rate: LR_UNKNOWN - 49 ms, 503 KB/s
24/05/2021 10:24:37 client_set_net: 127.0.0.1  0.0000
24/05/2021 10:24:37 created   xdamage object: 0x400033
24/05/2021 10:24:37 copy_tiles: allocating first_line at size 48
24/05/2021 10:24:47 created selwin: 0x400034
24/05/2021 10:24:47 called initialize_xfixes()
24/05/2021 10:25:01 XDAMAGE is not working well... misses: 85/202
24/05/2021 10:25:01 Maybe an OpenGL app like Beryl or Compiz is the problem?
24/05/2021 10:25:01 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
24/05/2021 10:25:01 To disable this check and warning specify -xdamage twice.
24/05/2021 10:27:58 XDAMAGE is not working well... misses: 155/228
24/05/2021 10:27:58 Maybe an OpenGL app like Beryl or Compiz is the problem?
24/05/2021 10:27:58 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
24/05/2021 10:27:58 To disable this check and warning specify -xdamage twice.
24/05/2021 10:28:11 client_count: 0
24/05/2021 10:28:11 Restored X server key autorepeat to: 1
24/05/2021 10:28:11 Client 127.0.0.1 gone
24/05/2021 10:28:11 Statistics             events    Transmit/ RawEquiv ( saved)
24/05/2021 10:28:11  ServerCutText       :      1 |         8/        8 (  0.0%)
24/05/2021 10:28:11  FramebufferUpdate   :    127 |         0/        0 (  0.0%)
24/05/2021 10:28:11  LastRect            :     79 |       948/      948 (  0.0%)
24/05/2021 10:28:11  tight               :   3690 |   4794802/160080148 ( 97.0%)
24/05/2021 10:28:11  TOTALS              :   3897 |   4795758/160081104 ( 97.0%)
24/05/2021 10:28:11 Statistics             events    Received/ RawEquiv ( saved)
24/05/2021 10:28:11  KeyEvent            :     12 |        96/       96 (  0.0%)
24/05/2021 10:28:11  PointerEvent        :    237 |      1422/     1422 (  0.0%)
24/05/2021 10:28:11  FramebufferUpdate   :    127 |      1270/     1270 (  0.0%)
24/05/2021 10:28:11  SetEncodings        :      1 |        52/       52 (  0.0%)
24/05/2021 10:28:11  SetPixelFormat      :      1 |        20/       20 (  0.0%)
24/05/2021 10:28:11  TOTALS              :    378 |      2860/     2860 (  0.0%)
24/05/2021 10:28:11 destroyed xdamage object: 0x400033

My docker create:
docker create \
--name=firefox \
-p 5801:5800 \
-e USER_ID=1001 -e GROUP_ID=998 \
-e DISPLAY_WIDTH=1500 -e DISPLAY_HEIGHT=930 \
-e TZ=America/New_York \
-v /opt/firefox:/config:rw \
-v /valhalla/downloads/complete:/downloads:rw \
-v /dev/shm:/dev/shm \
--security-opt seccomp=/valhalla/backup/docker/default.json \
jlesage/firefox

Please let me know if you need anything else to help diagnose this.

**Comment by jlesage** [comment]
Is the container stopping itself ?  I don't see that the container is stopping in the log...
Can you try to clear your browser's cache, or try to access the UI in a private/incognito window ?

**Comment by nzeminski** [comment]
Thanks for the recommendations. I typically try accessing this through Chrome on both a local network and on a VPN connection.
I have tried clearing cache in both the Firefox UI and any Chrome session I typically use. However the crashes/disconnects still happen. It could be my network or connection to a network perhaps I suppose.

25/05/2021 07:55:18 client_set_net: 127.0.0.1  0.0000
25/05/2021 07:55:23 client 35 network rate 377.8 KB/sec (37031.0 eff KB/sec)
25/05/2021 07:55:23 client 35 latency:  50.9 ms
25/05/2021 07:55:23 dt1: 0.0065, dt2: 0.1697 dt3: 0.0509 bytes: 56942
25/05/2021 07:55:23 link_rate: LR_UNKNOWN - 50 ms, 377 KB/s
25/05/2021 07:56:29 client_count: 0
25/05/2021 07:56:29 Restored X server key autorepeat to: 1
25/05/2021 07:56:29 Client 127.0.0.1 gone

**Comment by jlesage** [comment]
So same behaviour in an incognito window ?  Do you access the container directly (via the IP address of the host) or through a proxy ?

Which message do you have when you put your mouse pointer of the red X ?

You can also try to open the browser's developer tool and look at the console for error messages when the page is loading.

**Comment by nzeminski** [comment]
No crashes in an incognito window yet. I access the container directly via the IP of the host.
Next time I get a crash, I'll capture the rest of the information you requested.

**Comment by nzeminski** [comment]
The message I receive is "Server disconnected (code: 1006)"
![image](https://user-images.githubusercontent.com/60979973/119498140-4bf10300-bd33-11eb-8acd-7cb3bbbb139a.png)
I'll attach the full log but here is a screenshot of the errors:
![image](https://user-images.githubusercontent.com/60979973/119498493-aab67c80-bd33-11eb-93c7-c42e842e6af9.png)
[firefox-1621945812906.log](https://github.com/jlesage/docker-firefox/files/6539264/firefox-1621945812906.log)

**Comment by jlesage** [comment]
Ok, so if it's working in incognito window, the issue is really related to the browser's cache.  Make sure to clear files, cookies and any data associated to the site.

**Comment by nzeminski** [comment]
I can agree with that. I'll close this ticket and update with something new if I find anything else.
Thanks for all of your help!
