### ISSUE TITLE
The disk usage is very high on Windows Docker Desktop

### ISSUE THREAD

**Issue by miyouzi** [jlesage/docker-firefox#97]
The firefox in container is running very slow, and the disk usage is very high.

How to solve this problem ?

Docker Desktop v3.5.1 (base on WSL2)

docker command:
`
docker run --rm --name=firefox -p 5800:5800 -v D:\AppData\Docker\FireFox:/config:rw --mount type=bind,source=C:/Windows/Fonts,target=/usr/share/fonts/,readonly --shm-size 1g jlesage/firefox
`

use `--shm-size 2g` param had same problem

（Sorry for my bad english 😢）

![](https://user-images.githubusercontent.com/24269465/125756231-205af53f-ec80-4ca3-b48b-21de4c6ce75a.gif)

**Comment by jlesage** [comment]
Can you use the Windows Resource Monitor to check which file is being read/written ?

**Comment by miyouzi** [comment]
The problem disappear after I reboot.

I think it may cause by WSL memory setting which config file locate `%USERPROFILE%\.wslconfig`

At that time I had tried to upgrade `memory=1536MB` to `memory=4096MB` and restarted Docker but didn't reboot Windows. So the new config may not apply.

Then after reboot, the problem fixed.

Thank you for your reply !

My `%USERPROFILE%\.wslconfig` content is below
```
[wsl2]
memory=4096MB
swap=0
```
