### ISSUE TITLE
error mapping large iso file to idrac

### ISSUE THREAD

**Issue by bcharahr** [jlesage/docker-firefox#98]
error: Mediaworker acception on read: file to large

**Comment by bcharahr** [comment]
![2021-07-28_21-19-13](https://user-images.githubusercontent.com/36178096/127416861-ca16a552-8205-4cf9-bc2d-f213e619ea4a.jpg)

**Comment by jlesage** [comment]
What is the size of the iso file ?

**Comment by jlesage** [comment]
Closing this issue.  Please reopen if needed.
