### ISSUE TITLE
Download folder

### ISSUE THREAD

**Issue by m3xiz** [jlesage/docker-firefox#99]
It should be possible to assign a separate volume for the download folder, allowing a clear segregation between data and config.

Otherwise nice app,

**Comment by jlesage** [comment]
Volume mappings are configured while creating the container.  So users already have the ability to use a different volume for download purpose.

**Comment by m3xiz** [comment]
I realize it a little bit late but thanks. It works like a charm.

**Comment by bramus** [comment]
You can mount a different share in `/downloads` for example, and then set the preference to point to that folder.

```
docker run -d \
…
-v /local/path/to/downloads:/downloads:rw \
-e "FF_PREF_DOWNLOADS=browser.download.dir=\"\/downloads\"" \
…
jlesage/firefox
```

The only problem though: the container freaks out on it:

```
[cont-init.d] firefox-set-prefs-from-env.sh: Setting preference 'browser.download.dir'...
sed: bad option in substitution expression
```

As a workaround, mount the folder to `/config/downloads` **after** mounting a locale share to `/config`:

```
docker run -d \
…
-v /local/path/to/config:/config:rw \
-v /local/path/to/downloads:/config/downloads:rw \
…
jlesage/firefox
```

**Comment by LostOnTheLine** [comment]
> As a workaround, mount the folder to /config/downloads after mounting a locale share to /config:

The problem with this is that a mount point within another mount point has caused problems on some systems.

**Comment by iceman64128** [comment]
> Volume mappings are configured while creating the container. So users already have the ability to use a different volume for download purpose.

I feel like I search for 20h now, to configure the location of a different download folder. Could you please give me a hint?

**Comment by yamikeigo** [comment]
> You can mount a different share in `/downloads` for example, and then set the preference to point to that folder.
> 
> ```
> docker run -d \
> …
> -v /local/path/to/downloads:/downloads:rw \
> -e "FF_PREF_DOWNLOADS=browser.download.dir=\"\/downloads\"" \
> …
> jlesage/firefox
> ```
> 
> The only problem though: the container freaks out on it:
> 
> ```
> [cont-init.d] firefox-set-prefs-from-env.sh: Setting preference 'browser.download.dir'...
> sed: bad option in substitution expression
> ```
> 
> As a workaround, mount the folder to `/config/downloads` **after** mounting a locale share to `/config`:
> 
> ```
> docker run -d \
> …
> -v /local/path/to/config:/config:rw \
> -v /local/path/to/downloads:/config/downloads:rw \
> …
> jlesage/firefox
> ```

@jlesage  first of all, love all your containers...a

this workaround works, mapping a local folder location to the container downloads location. then I can ssh vIa filezilla and pull the file, but this is cumbersome. If I do a an external volume mappIng like I would for any other contaIner I get the following:

![lesage_ff](https://github.com/user-attachments/assets/e1b6fba7-46af-4af7-b111-be6e220d1930)

Oddly, when I have an external volume mapped to "/data/downloads" in the container I can ssh into the server, the container can see the volume contents and I can cp a file between that volume and the default downloads location of "/config/downloads", so I'm not sure where the permission issue lies.

I've tried the following mappings and neither work:

external_volume:/config/downloads:rw
external_volume:/data/downloads

the top one fails differently than the bottom one. the bottom one gives the pictured image, while the top method gives a "download failed" text from the download context section in the top menu bar of firefox

**Comment by jlesage** [comment]
Looks like the user you configured for the container (`USER_ID`/`GROUP_ID`) doesn't have the permission to write to the mounted folder. Double check the owner and permissions of the mounted folder.

**Comment by jlesage** [comment]
> The only problem though: the container freaks out on it:
> 
> ```
> [cont-init.d] firefox-set-prefs-from-env.sh: Setting preference 'browser.download.dir'...
> sed: bad option in substitution expression
> ```

`-e "FF_PREF_DOWNLOADS=browser.download.dir=\"/downloads\""` is working for me.

**Comment by yamikeigo** [comment]
> Looks like the user you configured for the container (`USER_ID`/`GROUP_ID`) doesn't have the permission to write to the mounted folder. Double check the owner and permissions of the mounted folder.

yeah that's why I first thought too, so I reverted to 0 from 1000

same error from both ID#s

**Comment by jlesage** [comment]
How did you create the external volume ?
Also, can you share the output of `docker exec <container name> ls -ld /data/downloads` ?

**Comment by yamikeigo** [comment]
> How did you create the external volume ? Also, can you share the output of `docker exec <container name> ls -ld /data/downloads` ?

drwxr-xr-x    2 root     root             0 Dec 28 17:08 /data/downloads


I created the external volume from the Volume section in Portainer. From my experience, that hasn't behaved differently from creating a volume via the 'docker create' command. I have dozens of volumes created in the same fashion without issue.

**Comment by yamikeigo** [comment]
here's my compose while I"m at it:

  firefox:
    container_name: firefox
    image: jlesage/firefox:v24.11.1
    restart: unless-stopped
    ports:
      - 5801:5800
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=America/Bromington
    volumes:
      - /data/compose/sourcing/firefox/config:/config:rw
      #- /data/compose/sourcing/firefox/downloads:/config/downloads:rw
      - external_volume:/data/downloads

**Comment by jlesage** [comment]
> drwxr-xr-x 2 root root 0 Dec 28 17:08 /data/downloads

Only the owner of the folder (i.e. `root`) have write access. If this is not expected, you can change the owner of the folder to match the one of the container:
```
docker exec <container name> chown -R <uid:gid> /data/downloads
```

Also:
> ```
> - PUID=0
> - PGID=0
> ```

Not sure where there are coming from, but these variables are not used. `USER_ID` and `GROUP_ID` should be used instead.

**Comment by yamikeigo** [comment]
> > drwxr-xr-x 2 root root 0 Dec 28 17:08 /data/downloads
> 
> Only the owner of the folder (i.e. `root`) have write access. If this is not expected, you can change the owner of the folder to match the one of the container:
> 
> ```
> docker exec <container name> chown -R <uid:gid> /data/downloads
> ```
> 
> Also:
> 
> > ```
> > - PUID=0
> > - PGID=0
> > ```
> 
> Not sure where there are coming from, but these variables are not used. `USER_ID` and `GROUP_ID` should be used instead.

Thank you! ok yeah I had the wrong variables. PUID and PGID are from other containers. Bad assumption on my part

**Comment by jlesage** [comment]
Perfect, I think we can close this issue if it's working for everybody.
